data["it"] = [
["scarno", "非常にやせた、やつれた", "N"],
["saettare", "（矢で）射る", "N"],
["pacca", "平手で叩くこと", "N"],
["trapelare", "（光・液体・秘密が）漏れる", "N"],
["spalluccia", "(fare spallucce)肩をすくめる ", "N"],
["scaraventare", "力いっぱい投げつける", "N"],
["ripiano", "平らな表面; 棚板 ", "N"],
["scemare", "減少する、弱まる、和らぐ", "N"],
["accartocciare", "筒状に巻く; しわくちゃにする", "N"],
["torvo", "（顔つきが）険しい", "N"],
["spregevole", "卑しむべき、卑劣な", "N"],
["squittire", "鋭く短く鳴く", "N"],
["grassoccio", "小太りの", "N"],
["rovistare", "くまなく探す, 探し回る ", "N"],
["calice", "杯、ゴブレット", "N"],
["impugnare", "握る、つかむ", "N"],
["balzo", "跳躍", "N"],
["squarciare", "裂く、破る", "N"],
["sfrecciare", "矢のように飛ぶ ", "N"],
["invogliare", "…に〈…したい〉気を起こさせる", "N"],
["vorticare", "渦を巻く, 風であちこち舞う ", "N"],
["zuffa", "乱闘、乱戦", "N"],
["piroettare", "ピルエットする, つま先で回る ", "N"],
["circospezione", "慎重さ ", "N"],
["mansione", "職務", "N"],
["appiattire", "平らにする", "N"],
["gracile", "華奢な、虚弱な", "N"],
["a cavalcioni", "またがって", "N"],
["sbuffare", "息が荒くなる、ため息をつく", "N"],
["solco", "溝、筋、しわ、わだち、航跡", "N"],
["fannullone", "怠け者、不精者", "N"],
["squadrare", "じろじろ眺める", "N"],
["polpastrello", "指の腹", "N"],
["accosciarsi", "しゃがむ", "N"],
["prepotente", "横暴な", "N"],
["laccio", "ひも", "N"],
["bighellonare", "ぶらつく、のらくら遊び暮らす", "N"],
["chiazza", "大きな丸い染み, よごれ ", "N"],
["insegna", "看板", "N"],
["stentare", "苦労する", "N"],
["mensola", "棚", "N"],
["trangugiare", "がつがつ飲み込む", "N"],
["possente", "権力のある、強力な", "N"],
["imbrattare", "〈…で〉汚す《di》", "N"],
["accavallare", "交差させる", "N"],
["fica", "（女性の）性器", "N"],
["caparbio", "強情な", "N"],
["scandire", "（詩などを）はっきり発音する", "N"],
["squagliare", "溶かす (再) 溶ける,こっそり逃げ出す ", "N"],
["bega", "小競り合い、面倒、やっかい", "N"],
["annichilire", "打ちのめす", "N"],
["tisana", "煎じ薬", "N"],
["ripostiglio", "物置", "N"],
["fardello", "大きな荷物、重荷", "N"],
["ineluttabile", "抗し得ない; 逃れられない ", "N"],
["stinco", "すね", "N"],
["sgranare", "さやをむく", "N"],
["cofano", "ボンネット、トランク", "N"],
["trafelato", "息を切らした ", "N"],
["incupire", "暗くする; （表情などを）陰うつにする", "N"],
["collaudo", "試験運転", "N"],
["natica", "臀部", "N"],
["accorato", "深く悲しんだ", "N"],
["svolgere", "（催しや活動を）行う, （役目を）果たす", "N"],
["incombere", "（重大事が）起ころうとしている", "N"],
["aleggiare", "羽ばたく、匂いが漂う", "N"],
["stantio", "（食べ物が）古くなった; 時代遅れの", "N"],
["sciatto", "だらしがない; 投げやりな", "N"],
["porticato", "アーケード、柱廊", "N"],
["penzolare", "ぶら下がる", "N"],
["zampillare", "ほとばしり出る", "N"],
["afflosciare", "ぐにゃぐにゃにする; 活力を奪う", "N"],
["trasalire", "身震いする, おののく ", "N"],
["perfido", "不実な、悪意のある", "N"],
["svignarsela", "逃げる、ずらかる", "N"],
["grondare", "流れ落ちる; したたる", "N"],
["irrequieto", "不安な、落ち着かない", "N"],
["desistere", "中止する、やめる", "N"],
["pastiglia", "錠剤", "N"],
["smaltire", "消化する、鎮める", "N"],
["scorgere", "気づく", "N"],
["lembo", "端、裾、一角", "N"],
["diradarsi", "希薄になる、まばらになる", "N"],
["lampante", "明白な", "N"],
["disappunto", "失望, 当て外れ", "N"],
["inveire", "罵倒する, ののしる ", "N"],
["spillare", "くみ出す", "N"],
["in quattro e quattr'otto", "一瞬のうちに", "N"],
["scagnozzo", "軽蔑語 貧しい司祭; 取り巻き; 子分", "N"],
["intraprendente", "積極的な、図々しい", "N"],
["monolocale", "ワンルーム", "N"],
["avvinghiare", "強くつかむ; 締め付ける (再)しがみつく", "N"],
["gruccia", "松葉杖; ハンガー", "N"],
["ciocca", "房", "N"],
["pisello", "エンドウ豆", "N"],
["inebetire", "鈍感にする; 唖然とさせる", "N"],
["mollare", "解放する、緩める、放棄する", "N"],
["tozzo", "ずんぐりした", "N"],
["megera", "鬼ばば, 醜い老婆", "N"],
["divincolarsi", "身をくねらせる, のたうつ ", "N"],
["rattrappire", "しびれさせる", "N"],
["astioso", "敵意に満ちた", "N"],
["inalberare", "掲げる", "N"],
["beccare", "くちばしでつつく、皮肉を言う", "N"],
["sbraitare", "怒鳴り散らす", "N"],
["sgambetto", "小またですたすた歩くこと", "N"],
["trafiletto", "囲み記事", "N"],
["rigoglioso", "繁茂した", "N"],
["putiferio", "大騒ぎ, けんか; 大混乱 ", "N"],
["sopraffare", "打ち負かす、圧倒する", "N"],
["spiegazzare", "しわくちゃにする", "N"],
["flaccido", "ぶよぶよした; 軟弱な ", "N"],
["rotella", "小さい車輪、ローラー、ころ", "N"],
["esubero", "過剰", "N"],
["recondito", "秘められた", "N"],
["tarchiato", "ずんぐりした", "N"],
["canicola", "真夏", "N"],
["in ghingheri", "しゃれた身なりで", "N"],
["parsimonioso", "つましい、質素な", "N"],
["affusolare", "紡錘形にする; 形よくする; 先を細くする", "N"],
["stelo", "茎; 軸; スタンド", "N"],
["beffardo", "からかい好きの ", "N"],
["calloso", "たこだらけの", "N"],
["fronda", "葉を付けた小枝、抵抗勢力", "N"],
["sgargiante", "鮮やかな, はでな ", "N"],
["lussureggiante", "豊穣な、豊かな", "N"],
["levigare", "磨く", "N"],
["impacchettare", "箱に入れる、捕まえる", "N"],
["allibire", "青ざめる; うろたえる", "N"],
["mettersi nei panni di", "〈人〉の立場になってみる", "N"],
["arrabattarsi", "あくせく働く ", "N"],
["raggranellare", "ぼつぼつ集める, かき集める ", "N"],
["caraffa", "カラフ, デキャンタ", "N"],
["cogitabondo", "物思いにふけった", "N"],
["cospicuo", "顕著な、著名な、おびただしい", "N"],
["rimbrottare", "厳しくとがめる", "N"],
["lavello", "流し; 洗面台 ", "N"],
["di botto", "いきなり", "N"],
["conato", "試み、努力", "N"],
["inerpicarsi", "よじ登る", "N"],
["bellicoso", "好戦的な; けんか好きの ", "N"],
["incallire", "…にたこを作る; 冷酷にする; 冷酷になる", "N"],
["redditizio", "利益になる, 収益の多い", "N"],
["grumo", "（血などの）かたまり", "N"],
["digrignare", "（歯を）むき出す ", "N"],
["civetteria", "媚; わざと人目を引く言動 ", "N"],
["appagare", "満足させる、かなえる", "N"],
["casermone", "みすぼらしいマンション", "N"],
["ossuto", "骨太い", "N"],
["a malincuore", "いやいやながら, しぶしぶと", "N"],
["stopposo", "麻くずのような", "N"],
["riscossione", "取り立て; （手形の）現金化 ", "N"],
["scriminatura", "頭髪の分け目 ", "N"],
["abboccare", "食いつく、引っかかる", "N"],
["additare", "指さす, 示す ", "N"],
["caseggiato", "共同住宅", "N"],
["battibecco", "言い争い ", "N"],
["ciottolo", "砂利", "N"],
["cunetta", "側溝", "N"],
["ruvido", "ざらざらした, 粗い", "N"],
["penzoloni", "ぶら下がって", "N"],
["ribrezzo", "嫌悪感、毛嫌い", "N"],
["fuseaux", "スパッツ ", "N"],
["mozzare", "切断する ", "N"],
["lombrico", "ミミズ ", "N"],
["gardenia", "クチナシ ", "N"],
["atlante", "頸椎", "N"],
["ingranare", "（歯車が）かみ合う;（人と）うまが合う", "N"],
["collant", "パンスト", "N"],
["civettuolo", "媚を含んだ; 人目を引く ", "N"],
["senape", "カラシ", "N"],
["gruzzolo", "蓄え", "N"],
["a fiotti", "大量に", "N"],
["seviziare", "虐待する; いじめる", "N"],
["escogitare", "考案する、案出する", "N"],
["brama", "熱望、渇望", "N"],
["miglio", "アワ、キビ", "N"],
["troneggiare", "高い席に座る; 君臨する; 偉そうにする", "N"],
["ematoma", "血腫 ", "N"],
["manopola", "（自転車のハンドルの）握り", "N"],
["truce", "残忍な, どう猛な", "N"],
["gingillarsi", "ぐずぐずする、時間浪費する", "N"],
["cialtrone", "いいかげんな人, だらしない奴", "N"],
["baldanzoso", "大胆な; 自信に満ちた", "N"],
["lampione", "街灯", "N"],
["stormire", "さらさらと鳴る", "N"],
["stizzire", "立腹させる, じらす; 腹を立てる", "N"],
["tralasciare", "省く", "N"],
["arrovellarsi", "(再) 怒る; いらだつ", "N"],
["pensilina", "（駅などの）差し掛け屋根 ", "N"],
["acquazzone", "激しいにわか雨", "N"],
["rizzare", "（まっすぐに）立てる; 起こす", "N"],
["bruco", "毛虫", "N"],
["spago", "ひも", "N"],
["giaculatoria", "短い絶叫的な祈り ", "N"],
["allacciare", "（ひもで）結ぶ、（ベルトを）締める", "N"],
["groviglio", "（糸などの）もつれ, からまり", "N"],
["annerire", "黒くする; 黒くなる", "N"],
["collottola", "うなじ", "N"],
["golfino", "短いセーター", "N"],
["bonifico", "送金", "N"],
["bussola", "磁石、羅針盤", "N"],
["spiazzo", "空き地", "N"],
["alla chetichella", "こっそり, ひそやかに", "N"],
["all'ultimo sangue", "命をかけた", "N"],
["brina", "霜", "N"],
["canaglia", "ごろつき、やくざ", "N"],
["rinfusa", "ばら荷/alla rinfusa ごちゃごちゃに ", "N"],
["felpato", "プラッシュの; 起毛の", "N"],
["propizio", "都合のよい", "N"],
["sgattaiolare", "こっそり抜け出す", "N"],
["tranello", "悪巧み", "N"],
["increspare", "しわを寄せる; ひだを付ける", "N"],
["rogo", "火事; 炎上", "N"],
["alone", "暈; オーラ", "N"],
["imposta", "税", "N"],
["sgusciare", "逃げ出す、逃れる", "N"],
["cigolare", "キーキー音を立てる、きしる", "N"],
["sarcofago", "石棺 ", "N"],
["felpa", "プラッシュ, フラシ天 ", "N"],
["divaricare", "二股に分ける, 分岐させる", "N"],
["tanica", "ポリタンク、燃料タンク", "N"],
["serranda", "シャッター", "N"],
["giochetto", "単純な遊び", "N"],
["voluta", "渦巻き", "N"],
["calca", "雑踏, 群衆", "N"],
["cupidigia", "どん欲さ", "N"],
["carretto", "手押し車、屋台", "N"],
["tamburello", "タンバリン、ラケット", "N"],
["scorticare", "皮をむく、すりむく", "N"],
["predisporsi", "覚悟する", "N"],
["bancarella", "屋台", "N"],
["formicolio", "混雑、雑踏", "N"],
["peschereccio", "漁業の", "N"],
["ortaggio", "野菜類", "N"],
["sganciarsi", "はずれる、手を切る", "N"],
["incalzare", "追い立てる、せき立てる", "N"],
["frullare", "羽ばたく、かき混ぜる", "N"],
["traguardo", "ゴール、到着点", "N"],
["dileguarsi", "消える", "N"],
["fiacca", "疲労、無気力", "N"],
["comizio", "政治集会", "N"],
["nocciolina", "小さなナッツ類", "N"],
["manovale", "下働き、肉体労働者", "N"],
["calvario", "長い苦難", "N"],
["maniglia", "取っ手、ノブ", "N"],
["destare", "目を覚まさせる、呼び起こす", "N"],
["scarabocchio", "汚れ、殴り書き", "N"],
["cancellata", "（建物を取り巻く）柵", "N"],
["sgombro", "サバ", "N"],
["sfrattare", "立ち退かせる、追い出す", "N"],
["giuntura", "連結、接合、間接", "N"],
["rosticceria", "総菜屋、デリカテッセン", "N"],
["tettoia", "ひさし", "N"],
["filastrocca", "童謡、わらべ歌", "N"],
["forfora", "ふけ", "N"],
["gazza", "カササギ", "N"],
["trabocchetto", "落とし穴、罠", "N"],
["scrofa", "雌豚", "N"],
["scure", "斧、まさかり", "N"],
["fanale", "標識灯、ライト", "N"],
["agrume", "柑橘類", "N"],
["guardingo", "慎重な、用心深い", "N"],
["spavaldo", "生意気な、厚かましい", "N"],
["fenicottero", "フラミンゴ", "N"],
["infarto", "梗塞", "N"],
["striscia", "帯状の物、細長い一片", "N"],
["edicolante", "店員、店主", "N"],
["sommozzatore", "潜水夫", "N"],
["allarmarsi", "動揺する", "N"],
["birichino", "腕白な、やんちゃ坊主", "N"],
["pennarello", "フェルトペン", "N"],
["ringhiare", "歯をむき出してうなる", "N"],
["zotico", "粗野な、不作法な", "N"],
["caviglia", "くるぶし", "N"],
["rigattiere", "古物商", "N"],
["solletico", "くすぐったい感じ", "N"],
["melanzana", "なす", "N"],
["stufo", "飽き飽きした", "N"],
["scimmiottare", "真似をする", "N"],
["cipria", "おしろい", "N"],
["ottuso", "鈍い、鈍感な", "N"],
["a bruciapelo", "至近距離で、いきなり", "N"],
["calpestare", "踏みつける", "N"],
["marcio", "腐った、化膿した", "N"],
["sottrarsi", "免れる", "N"],
["avvitare", "ねじで留める", "N"],
["recapitare", "発送する", "N"],
["dozzina", "ダース", "N"],
["genero", "婿", "N"],
["aceto", "酢", "N"],
["tovagliolo", "ナプキン", "N"],
["estirpare", "根絶する", "N"],
["museruola", "（馬の）口輪", "N"],
["imbranato", "不器用な", "N"],
["groppa", "背中", "N"],
["grossolano", "粗末な、粗野な", "N"],
["frantume", "破片", "N"],
["zuccone", "バカ、石頭", "N"],
["temperino", "鉛筆削り", "N"],
["formicaio", "アリの巣", "N"],
["corazzata", "戦艦", "N"],
["macinarsi", "身を粉にする", "N"],
["burrasca", "時化", "N"],
["pagnotta", "丸いパン", "N"],
["lavagna", "黒板", "N"],
["sportello", "小さな扉", "N"],
["spremere", "絞り出す", "N"],
["scottare", "やけどさせる", "N"],
["tovaglia", "テーブルクロス", "N"],
["filone", "鉱脈、思潮", "N"],
["frugoletto", "やんちゃ坊主", "N"],
["sporgersi", "身を乗り出す", "N"],
["lampone", "木イチゴ", "N"],
["stroncare", "折る", "N"],
["grandine", "ひょう、あられ", "N"],
["marmellata", "ジャム", "N"],
["giglio", "百合", "N"],
["camerata", "共同寝室、サークル", "N"],
["zucca", "カボチャ", "N"],
["strenna", "プレゼント", "N"],
["intrecciare", "編む、結び合わす", "N"],
["divario", "相違、ギャップ", "N"],
["mancino", "左利きの", "N"],
["morsa", "万力", "N"],
["gota", "ほほ", "N"],
["fieno", "干し草、まぐさ", "N"],
["posacenere", "灰皿", "N"],
["pacchia", "楽しい時間", "N"],
["lungomare", "海岸通り", "N"],
["cannuccia", "ストロー", "N"],
["calmiere", "公定価格", "N"],
["soffice", "柔らかい", "N"],
["stento", "（複）生活苦、貧困、苦労", "N"],
["reparto", "部門、売り場", "N"],
["cozza", "ムール貝", "N"],
["ressa", "混雑、人混み", "N"],
["micio", "子猫", "N"],
["dado", "さいころ", "N"],
["cannocchiale", "望遠鏡", "N"],
["pedone", "歩行、歩兵", "N"],
["trebbiare", "脱穀する", "N"],
["rombo", "菱形、ヒラメ", "N"],
["tafano", "アブ", "N"],
["trave", "梁", "N"],
["incrinarsi", "ひび割れる", "N"],
["cuccagna", "豊穣、贅沢三昧", "N"],
["foraggio", "飼料", "N"],
["pidocchio", "シラミ", "N"],
["gradito", "うれしい、大歓迎の", "N"],
["ticcio", "気まぐれ、衝動的な欲望", "N"],
["scalpello", "のみ、たがね", "N"],
["molletta", "洗濯ばさみ", "N"],
["scheggia", "破片、かけら", "N"],
["polsino", "袖口、カフス", "N"],
["gianduiotto", "ナッツ入りチョコレート", "N"],
["ripiego", "便利な方法", "N"],
["mortaio", "乳鉢、すり鉢", "N"],
["arachide", "ピーナッツ", "N"],
["edilizia", "建築、建築技術", "N"],
["barcamenarsi", "臨機応変に対処する", "N"],
["piazzista", "セールスマン", "N"],
["pepita", "天然の金塊", "N"],
["sorcio", "ネズミ", "N"],
["lepre", "野ウサギ", "N"],
["finocchio", "ウイキョウ", "N"],
["scherma", "フェンシング", "N"],
["catasta", "（物の）山", "N"],
["rassettare", "整理する", "N"],
["rissa", "乱闘、激論", "N"],
["svogliato", "やる気のない、無気力な", "N"],
["crusca", "ぬか、ふすま、ブラン", "N"],
["risciacquare", "すすぎ落とす", "N"],
["vampata", "紅潮", "N"],
["zappare", "耕す", "N"],
["strapiombo", "断崖、絶壁", "N"],
["trebbiatrice", "脱穀機", "N"],
["locandina", "ビラ、チラシ", "N"],
["sponda", "岸、端", "N"],
["forsennato", "常軌を逸した、狂った", "N"],
["stuoia", "マット、むしろ", "N"],
["ciambella", "ドーナツ、おしゃぶり、浮き輪", "N"],
["rosicchiare", "かじる", "N"],
["profilarsi", "迫る、差し迫る", "N"],
["truffare", "だまし取る", "N"],
["battello", "小型の汽船", "N"],
["femore", "太もも", "N"],
["lusingare", "おだてる、その気にさせる", "N"],
["giostra", "回転木馬、騎馬試合", "N"],
["lussazione", "脱臼", "N"],
["palude", "沼、湿原", "N"],
["scossa", "揺れ、振動", "N"],
["fogna", "下水道、排水溝", "N"],
["babbuino", "ヒヒ", "N"],
["dispetto", "意地悪", "N"],
["schierare", "配置する、整列させる", "N"],
["viscere", "内臓", "N"],
["intrallazzo", "闇取引", "N"],
["faraona", "ホロホロチョウ", "N"],
["manubrio", "（自転車の）ハンドル", "N"],
["rame", "銅", "N"],
["rivendicare", "強く求める、主張する", "N"],
["ficcanaso", "おせっかいな", "N"],
["rapina", "強盗", "N"],
["mietere", "刈り取る", "N"],
["barella", "担架", "N"],
["macchia", "やぶ、茂み", "N"],
["bavero", "襟", "N"],
["gergo", "隠語", "N"],
["garbato", "礼儀正しい", "N"],
["spruzzarsi", "しぶきにかかる", "N"],
["badile", "シャベル", "N"],
["stagno", "池、水たまり、スズ", "N"],
["scroccone", "たかる人", "N"],
["tintarella", "日焼け", "N"],
["suppellettile", "家具、調度品", "N"],
["solleticare", "くすぐる、刺激する", "N"],
["pergola", "つる棚", "N"],
["conciato", "無残な、やつれ果てた", "N"],
["capolino", "花弁", "N"],
["pergolato", "（長く大きな）棚", "N"],
["bastimento", "貨物船", "N"],
["ricamo", "刺繍", "N"],
["gattopardo", "山猫", "N"],
["inquinare", "汚染する、腐敗させる", "N"],
["borraccia", "水筒", "N"],
["stoviglie", "食器類", "N"],
["scaturire", "ほとばしり出る", "N"],
["pipistrello", "コウモリ", "N"],
["fumaiolo", "煙突", "N"],
["impalcatura", "足場、骨組み", "N"],
["ermetico", "密封された", "N"],
["sfegatato", "熱狂的な、猛烈な", "N"],
["calzamaglia", "タイツ", "N"],
["fattorino", "雑用係、配達係", "N"],
["ruffa", "殺到、もみ合い、大混乱", "N"],
["orecchino", "イヤリング", "N"],
["bestemmia", "冒涜的な言葉", "N"],
["panca", "ベンチ", "N"],
["montone", "雄羊", "N"],
["abbigliamento", "衣服", "N"],
["ringhiera", "手すり、欄干", "N"],
["lampadario", "シャンデリア", "N"],
["capriola", "飛び跳ねること、前転", "N"],
["pinna", "ひれ", "N"],
["detrito", "破片、くず", "N"],
["stregone", "呪術師、祈祷師", "N"],
["slavina", "雪崩", "N"],
["intonaco", "漆喰、プラスター", "N"],
["bottegaio", "商店主、商人", "N"],
["forcina", "ヘアピン", "N"],
["zizzania", "毒麦", "N"],
["vagire", "泣く、産声を上げる", "N"],
["fanteria", "歩兵隊", "N"],
["grondaia", "樋", "N"],
["catrame", "タール", "N"],
["estenuare", "くたびれさせる", "N"],
["corteccia", "樹皮", "N"],
["vigliaccheria", "臆病、卑怯", "N"],
["mignolo", "小指", "N"],
["quaglia", "ウズラ", "N"],
["fodero", "さや", "N"],
["gavetta", "飯ごう", "N"],
["bersagliere", "狙撃兵", "N"],
["franchigia", "特権、免除", "N"],
["agonismo", "競争心、闘魂", "N"],
["bustarella", "賄賂、リベート", "N"],
["riccorenza", "記念日", "N"],
["rompiscatole", "厄介者、うるさい人", "N"],
["bombola", "ボンベ", "N"],
["ricciolo", "巻き毛", "N"],
["istrice", "ヤマアラシ", "N"],
["ronzio", "（虫の）ブーンという音", "N"],
["farabutto", "破廉恥漢、悪人、ごろつき", "N"],
["rozzo", "不作法な、教養のない、荒削りな", "N"],
["guancialetto", "パッド、詰め物", "N"],
["seguace", "信奉者、従者", "N"],
["materasso", "敷き布団、マットレス", "N"],
["broncio", "ふくれっ面、仏頂面", "N"],
["suino", "豚、豚の", "N"],
["locanda", "安宿", "N"],
["cafone", "無教養な、がさつな", "N"],
["fasullo", "偽の、粗悪な", "N"],
["insospettirsi", "疑う、怪しむ", "N"],
["antefatto", "先例、前歴", "N"],
["calcagno", "かかと", "N"],
["pagliaccio", "ピエロ", "N"],
["frantumare", "粉々にする", "N"],
["scansare", "遠ざける、避ける", "N"],
["mite", "温和な、穏やかな", "N"],
["camorra", "暴力団", "N"],
["tetro", "暗い、陰気な", "N"],
["sonaglio", "鈴", "N"],
["pozzanghera", "ぬかるみ", "N"],
["cospargere", "まき散らす、覆う", "N"],
["falce", "鎌", "N"],
["nolo", "輸送費、チャーター料金", "N"],
["ghiacciolo", "つらら、アイスキャンデー", "N"],
["mangime", "えさ、飼料", "N"],
["reato", "犯罪", "N"],
["spranga", "かんぬき", "N"],
["rocchetto", "糸巻き", "N"],
["arretrato", "遅れた、時代遅れの", "N"],
["loculo", "墓穴、納骨堂", "N"],
["birillo", "（ボーリングの）ピン、（道路の）コーン", "N"],
["stampella", "松葉杖、ハンガー", "N"],
["snello", "軽快な", "N"],
["cimice", "南京虫", "N"],
["pollame", "家禽類", "N"],
["carriola", "手押しの一輪車", "N"],
["cuccia", "犬小屋", "N"],
["scappatoia", "逃げ道、抜け道", "N"],
["brano", "断片、一部、曲", "N"],
["occhiello", "小さな穴", "N"],
["anca", "腰", "N"],
["velluto", "ビロード", "N"],
["pustola", "おでき、できもの", "N"],
["rigovernare", "洗い物をする、後片付けをする", "N"],
["orata", "黒鯛", "N"],
["belva", "野獣", "N"],
["gobba", "猫背、こぶ", "N"],
["giara", "壺、かめ", "N"],
["pasticcino", "小さなケーキ", "N"],
["tapparella", "ロールカーテン", "N"],
["imbrogliarsi", "もつれる、混乱する", "N"],
["pratellina", "野菊", "N"],
["strofinaccio", "雑巾", "N"],
["calabrone", "スズメバチ", "N"],
["srotolare", "開く、広げる", "N"],
["bisticciare", "言い争う", "N"],
["zattera", "筏", "N"],
["cocciuto", "頑固な", "N"],
["appannarsi", "曇る、ぼやける", "N"],
["rigovernatura", "洗い物", "N"],
["brace", "炭火", "N"],
["sfociare", "流れ込む、通じる、もたらす", "N"],
["bianchetto", "漂白剤、白くする物", "N"],
["serbarsi", "保つ", "N"],
["poggio", "丘陵、小高い丘", "N"],
["nibbio", "鳶", "N"],
["sguaiato", "行儀の悪い、見苦しい", "N"],
["spaccone", "ほら吹き", "N"],
["barbone", "プードル、浮浪者", "N"],
["sprecone", "浪費家", "N"],
["cornetta", "受話器", "N"],
["brandello", "切れ端、ぼろきれ", "N"],
["ufo", "ただで、無料で", "N"],
["bengodi", "桃源郷、極楽", "N"],
["tegame", "（浅い）鍋", "N"],
["raccapriccio", "身震い、戦慄", "N"],
["sciupone", "浪費家", "N"],
["alluce", "（足の）親指", "N"],
["fibbia", "締め金、留め金", "N"],
["frugare", "隅々まで探す、探し回る", "N"],
["cavalletta", "バッタ、イナゴ", "N"],
["raffica", "突風、連発、連射", "N"],
["fifone", "恐がり", "N"],
["spuntino", "軽食、間食", "N"],
["sporta", "買い物かご", "N"],
["scapito", "損害、損失", "N"],
["rabbrividire", "震える、身震いする", "N"],
["dimesso", "控えめな、貧弱な、みすぼらしい", "N"],
["concime", "肥料", "N"],
["balocco", "おもちゃ", "N"],
["mortaretto", "爆竹", "N"],
["moscerino", "（群がって飛ぶ）小さな虫", "N"],
["stropicciarsi", "こする、しわくちゃにする", "N"],
["barzelletta", "笑い話、冗談", "N"],
["piccozza", "ピッケル", "N"],
["straziare", "苦しめる、引き裂く", "N"],
["spruzzare", "吹きかける、スプレーする", "N"],
["singhiozzo", "しゃっくり", "N"],
["grattugia", "おろし金", "N"],
["acconciatura", "髪型", "N"],
["struzzo", "ダチョウ", "N"],
["appalto", "入札、請負", "N"],
["sciagura", "大惨事、大事故", "N"],
["schiantarsi", "激突して大破する", "N"],
["sedano", "セロリ", "N"],
["bretella", "サスペンダー", "N"],
["vascello", "大型帆船", "N"],
["vanga", "鋤、鍬", "N"],
["stoppa", "麻くず", "N"],
["brevetto", "特許", "N"],
["baco", "幼虫、バグ", "N"],
["murena", "ウツボ", "N"],
["escoriazione", "擦り傷", "N"],
["spiraglio", "小さな明かり", "N"],
["indaffarato", "忙しい", "N"],
["boccale", "水差し、ジョッキ", "N"],
["sghembo", "斜めの、ゆがんだ", "N"],
["risaia", "水田", "N"],
["selciato", "舗装した、石畳の", "N"],
["mugnaio", "粉屋", "N"],
["prosciugare", "干す、干拓する、乾かす", "N"],
["paperone", "富豪", "N"],
["accattone", "乞食", "N"],
["burrone", "崖、絶壁", "N"],
["meridiana", "日時計", "N"],
["bacca", "液果、小さな果実", "N"],
["acero", "カエデ、もみじ", "N"],
["podere", "農家、農場", "N"],
["russare", "いびきをかく", "N"],
["lenza", "釣り糸", "N"],
["maresciallo", "元帥、准士官", "N"],
["brigantaggio", "強盗行為", "N"],
["aragosta", "伊勢エビ", "N"],
["torchio", "圧搾機", "N"],
["sughero", "コルク", "N"],
["ganascia", "あご", "N"],
["impacciato", "混乱した", "N"],
["bufera", "嵐、暴風雨", "N"],
["pannolino", "おむつ、生理用ナプキン", "N"],
["pupazzo", "人形、操り人形", "N"],
["cocomero", "スイカ", "N"],
["ingombrante", "場所を取る、じゃまになる", "N"],
["vetta", "頂上、頂点、絶頂", "N"],
["dentice", "タイ", "N"],
["altalena", "ブランコ、シーソー", "N"],
["rimorchio", "トレーラー、牽引", "N"],
["siepe", "生け垣", "N"],
["bettola", "安酒場", "N"],
["bracco", "猟犬", "N"],
["crociatta", "十字軍、撲滅運動", "N"],
["pinolo", "松の実", "N"],
["squama", "うろこ", "N"],
["abbaino", "屋根裏、屋根窓", "N"],
["bolla", "泡", "N"],
["corva", "カラス", "N"],
["ruttare", "げっぷをする", "N"],
["muffa", "カビ", "N"],
["fio", "年貢", "N"],
["gemma", "芽、宝石", "N"],
["schietto", "純粋な、誠実な", "N"],
["spaccio", "売店、密売", "N"],
["granchio", "カニ", "N"],
["mattarello", "麺棒", "N"],
["corsaro", "海賊", "N"],
["barattolo", "瓶", "N"],
["botta", "殴打、打撲", "N"],
["battipanni", "はたき", "N"],
["mirtillo", "ブルーベリー", "N"],
["ossequio", "敬意", "N"],
["cicca", "吸い殻、チューインガム", "N"],
["teglia", "（オーブン用）平鍋", "N"],
["tramezzino", "サンドイッチ", "N"],
["cassata", "果物・ナッツ入りのアイスクリーム", "N"],
["lentiggine", "そばかす、しみ", "N"],
["rocca", "糸巻き棒", "N"],
["sprone", "拍車", "N"],
["succhiello", "錐", "N"],
["bavaglio", "さるぐつわ", "N"],
["carciofo", "アーティチョーク", "N"],
["perno", "軸、中軸", "N"],
["portacipria", "コンパクト", "N"],
["teschio", "頭蓋", "N"],
["branchia", "えら", "N"],
["piaga", "切り傷", "N"],
["ruscello", "小川", "N"],
["catinella", "洗面器", "N"],
["piastra", "（金属や石の）板、プレート", "N"],
["coricarsi", "横になる、寝る", "N"],
["puzzola", "イタチ", "N"],
["schiuma", "泡、よだれ", "N"],
["scenata", "叱責、非難", "N"],
["pianterreno", "1階", "N"],
["capanno", "脱衣場、漁師小屋", "N"],
["sciagurato", "悲惨な、痛ましい", "N"],
["sbirciare", "盗み見する、のぞく", "N"],
["borgata", "ニュータウン、ベッドタウン", "N"],
["ammiccare", "目配せする、ウィンクする", "N"],
["gengiva", "歯茎、歯肉", "N"],
["ventaglio", "扇子、扇", "N"],
["prezzemolo", "パセリ", "N"],
["ragnatela", "蜘蛛の巣", "N"],
["pelato", "はげた", "N"],
["garza", "ガーゼ、（鳥の）サギ", "N"],
["dirotto", "すさまじい、猛烈な", "N"],
["congegno", "装置、仕掛け", "N"],
["tavolozza", "パレット", "N"],
["luccicare", "光る、輝く", "N"],
["navetta", "シャトル便、連絡便", "N"],
["spicchio", "一袋、一切れ", "N"],
["parato", "壁飾り", "N"],
["gingillo", "おもちゃ、がらくた", "N"],
["indiviso", "共有の、共同所有の", "N"],
["tartufo", "トリュフ", "N"],
["sprecarsi", "無駄骨を折る", "N"],
["ascesso", "おでき", "N"],
["parolaccia", "悪い言葉、下品な言葉", "N"],
["pinza", "ペンチ、（甲殻類の）ハサミ", "N"],
["ossobuco", "仔牛のすね肉の料理", "N"],
["borgo", "村", "N"],
["tachimetro", "速度計、走行計、メーター", "N"],
["a casaccio", "でたらめに、ランダムに", "N"],
["mucca", "乳牛", "N"],
["razzo", "打ち上げ花火、ロケット弾", "N"],
["piccione", "鳩", "N"],
["gomitolo", "糸の玉", "N"],
["roulotte", "トレーラーハウス", "N"],
["davanzale", "窓の台", "N"],
["lucchetto", "南京錠", "N"],
["fesso", "ばかげた、くだらない", "N"],
["travaglio", "苦痛、苦悩、重労働", "N"],
["greggio", "原料のままの、未加工の", "N"],
["fionda", "ぱちんこ、石鉄砲", "N"],
["storione", "チョウザメ", "N"],
["sterzare", "ハンドルを切る", "N"],
["rugiada", "露", "N"],
["fantino", "騎手", "N"],
["beniamino", "秘蔵っ子、アイドル", "N"],
["panettone", "ケーキパン", "N"],
["spacciato", "絶望的な", "N"],
["libeccio", "南西、南西から吹く風", "N"],
["gagliardo", "強い、勇敢な", "N"],
["canottiera", "ランニングシャツ", "N"],
["cazzuola", "（左官の）こて", "N"],
["raganella", "アマガエル、がらがら", "N"],
["molo", "防波堤、桟橋", "N"],
["cece", "ひよこ豆", "N"],
["glicine", "藤", "N"],
["biada", "餌、飼葉", "N"],
["fune", "綱、ロープ", "N"],
["appiccicare", "貼る、のり付けする", "N"],
["baffo", "口ひげ", "N"],
["groviera", "あばら家", "N"],
["appassito", "しおれた、色あせた", "N"],
["rosolia", "風疹", "N"],
["vimine", "細枝、つる", "N"],
["rotta", "航路", "N"],
["cicogna", "コウノトリ", "N"],
["raccapricciante", "おぞましい、ぞっとするような", "N"],
["guadare", "（浅瀬を）歩いて渡る", "N"],
["bernoccolo", "こぶ、才能", "N"],
["aquilone", "凧、ハンググライダー", "N"],
["sproposito", "軽率な行動、ひどい間違い", "N"],
["malva", "葵、薄紫", "N"],
["brigadiere", "巡査長", "N"],
["sigillo", "印章、シール、封印", "N"],
["spalliera", "（椅子の）背もたれ", "N"],
["airone", "サギ", "N"],
["prestigiatore", "手品師、魔術師", "N"],
["tosare", "（毛を）刈る", "N"],
["scalo", "寄港地", "N"],
["differire", "延期する", "N"],
["cruscotto", "ダッシュボード、計器板", "N"],
["prugna", "プラム", "N"],
["strillare", "わめく、怒鳴る", "N"],
["insidia", "罠、待ち伏せ", "N"],
["sogliola", "シタビラメ", "N"],
["morbillo", "はしか", "N"],
["dotto", "学識のある、博学な", "N"],
["ciglio", "目の縁、まつげ", "N"],
["polpaccio", "ふくらはぎ", "N"],
["gesta", "（複）武勲、功績", "N"],
["sfumatura", "微妙な意味合い、ニュアンス", "N"],
["inciampo", "障害、障害物", "N"],
["dilagare", "氾濫する、あふれる", "N"],
["mammella", "乳房", "N"],
["veglione", "（夜通しの）舞踏会", "N"],
["toppa", "当て布、鍵穴、応急処置", "N"],
["fiocco", "ちょうちょ結び、毛玉", "N"],
["patibolo", "死刑、死刑台", "N"],
["scampo", "救い、逃げ道", "N"],
["alveare", "ミツバチの巣、巣箱", "N"],
["viottolo", "細道、小道", "N"],
["sella", "サドル、鞍", "N"],
["appiglio", "手がかり、口実", "N"],
["pulcino", "ひよこ", "N"],
["corredo", "必需品一式、用具一式", "N"],
["scrosciare", "（雨が）激しく降る", "N"],
["lancetta", "（時計などの）針", "N"],
["bestiame", "家畜", "N"],
["pigione", "賃貸料、家賃", "N"],
["basetta", "もみあげ", "N"],
["spezzare", "粉砕する、分断する", "N"],
["granturco", "トウモロコシ", "N"],
["riccio", "ハリネズミ", "N"],
["doppione", "重複品、副本、複製", "N"],
["scapolo", "（男性の）独身", "N"],
["intasarsi", "詰まる", "N"],
["civetta", "フクロウ", "N"],
["tornaconto", "利益、得、報い", "N"],
["lontra", "カワウソ", "N"],
["soprabito", "薄手のコート", "N"],
["redini", "手綱、主導権", "N"],
["volpone", "狡猾な人、悪賢い人", "N"],
["biscia", "蛇", "N"],
["sipario", "幕、緞帳", "N"],
["vettovaglie", "食糧", "N"],
["palombaro", "潜水夫", "N"],
["edera", "ツタ", "N"],
["ombelico", "へそ", "N"],
["daino", "鹿", "N"],
["pialla", "かんな", "N"],
["crostino", "クルトン、カナッペ", "N"],
["giovarsi", "活用する、役立てる", "N"],
["spatola", "へら、こて", "N"],
["frana", "山崩れ、地滑り", "N"],
["annaffiatoio", "じょうろ", "N"],
["sciame", "ミツバチの群れ、大群", "N"],
["pece", "ピッチ、松ヤニ", "N"],
["chicco", "穀粒、粒", "N"],
["trottola", "こま", "N"],
["chiocciola", "カタツムリ", "N"],
["tegola", "屋根瓦", "N"],
["trina", "（織）レース", "N"],
["cavalcavia", "陸橋", "N"],
["fauci", "口腔、口", "N"],
["scoiattolo", "リス", "N"],
["babbeo", "間抜け、お人好し", "N"],
["lordo", "汚い、総額の", "N"],
["staffa", "あぶみ、踏み板、ペダル", "N"],
["tuta", "（上下のつながった）作業着、つなぎ", "N"],
["fantoccio", "（等身大の）人形、でくの坊", "N"],
["stamberga", "あばら家、掘っ立て小屋", "N"],
["inciampare", "つまずく、よろける", "N"],
["grigiore", "わびしさ、もの悲しさ", "N"],
["sbieco", "斜めの、傾いた", "N"],
["segheria", "製材所", "N"],
["orma", "足跡、痕跡、跡", "N"],
["puntiglio", "片意地、意固地", "N"],
["coccinella", "テントウムシ", "N"],
["sfavillante", "きらめく、きらきら光る", "N"],
["veniale", "（罪過が）軽い、許しうる", "N"],
["palpebra", "まぶた", "N"],
["piroscafo", "汽船、蒸気船", "N"],
["strofinarsi", "こする、すり寄る", "N"],
["furfante", "悪党、ならず者", "N"],
["manganello", "棍棒、警棒", "N"],
["ciabattina", "ゴム草履", "N"],
["padella", "フライパン", "N"],
["rebus", "不可解な事件、謎", "N"],
["grinza", "しわ", "N"],
["schiamazzare", "騒ぐ、バカ騒ぎする", "N"],
["stanare", "穴から追い出す、連れ出す", "N"],
["impicciarsi", "口出しする、かまう", "N"],
["ghiotto", "食いしん坊の、食欲をそそる", "N"],
["valicare", "（国境や山を）越える", "N"],
["steccato", "木の囲い、柵", "N"],
["ghiandola", "分泌腺", "N"],
["accappatoio", "バスローブ", "N"],
["paraurti", "バンパー", "N"],
["rovo", "イバラ、木イチゴ", "N"],
["tracolla", "（肩から斜めにかける）帯", "N"],
["permaloso", "怒りっぽい、短気な", "N"],
["cornacchia", "カラス", "N"],
["catino", "たらい、洗面器、盆地", "N"],
["nicchia", "くつろげる場所、待避所、ニッチ", "N"],
["banchina", "（駅の）ホーム", "N"],
["pezzuola", "（傷口などに巻く）布", "N"],
["capannone", "倉庫、ガレージ", "N"],
["ascella", "脇", "N"],
["faggio", "ブナ", "N"],
["fagiolino", "サヤインゲン", "N"],
["valico", "峠", "N"],
["rasciare", "磨く、こすり取る", "N"],
["ammucchiare", "積み上げる、山積みする", "N"],
["sopruso", "権力の乱用、権利の乱用", "N"],
["prurito", "かゆみ", "N"],
["sbriciolare", "粉々にする、粉砕する", "N"],
["squarcio", "裂け目、裂傷", "N"],
["ghianda", "ドングリ", "N"],
["diga", "ダム、防御", "N"],
["bossolo", "薬莢", "N"],
["siluro", "魚雷", "N"],
["rincrescere", "残念に思う、嫌な思いをする", "N"],
["zuzzurellone", "のんきな人、子供のような人", "N"],
["pagella", "通信簿", "N"],
["battona", "売春婦", "N"],
["rapa", "カブ", "N"],
["pancciotto", "チョッキ、ベスト", "N"],
["piffero", "横笛", "N"],
["faluto", "笛、フルート", "N"],
["caserma", "兵舎", "N"],
["guaina", "さや", "N"],
["papera", "若い雌のガチョウ、小娘", "N"],
["cetriolo", "キュウリ", "N"],
["goloso", "～が大好物の", "N"],
["vitello", "子牛、子牛の肉", "N"],
["scavalcare", "飛び越える、凌駕する", "N"],
["favo", "蜂の巣", "N"],
["agguato", "罠、待ち伏せ", "N"],
["a vanvera", "でまかせに、でたらめに", "N"],
["squalo", "サメ", "N"],
["meschino", "浅ましい、さもしい", "N"],
["ruzzolone", "転倒、転落", "N"],
["pompelmo", "グレープフルーツ", "N"],
["balia", "乳母、里親", "N"],
["ustionarsi", "やけどする", "N"],
["ravanello", "ラディッシュ", "N"],
["palmipede", "水鳥", "N"],
["bivio", "分岐点、分かれ道", "N"],
["frasca", "葉の茂った枝", "N"],
["porgere", "差し出す、提供する、与える", "N"],
["luccio", "カワカマス", "N"],
["patire", "苦しむ、耐える、我慢する", "N"],
["accetta", "斧", "N"],
["frodo", "密輸", "N"],
["papavero", "ケシ", "N"],
["cavia", "モルモット、実験材料", "N"],
["rene", "腎臓", "N"],
["felce", "シダ", "N"],
["grissino", "乾パン", "N"],
["cordicella", "ひも", "N"],
["prudere", "かゆい", "N"],
["baita", "山小屋", "N"],
["zingaro", "ジプシー", "N"],
["canocchia", "シャコ", "N"],
["valanga", "なだれ、大量、洪水", "N"],
["goffo", "ぎこちない、見苦しい", "N"],
["baratto", "物々交換、バーター", "N"],
["mendicante", "乞食", "N"],
["germoglio", "新芽、若芽", "N"],
["ciuffo", "長い房、茂み", "N"],
["ghisa", "鋳鉄", "N"],
["stampatello", "活字体、活字体の", "N"],
["indivia", "サラダ菜", "N"],
["giaggiolo", "アヤメ", "N"],
["esca", "餌", "N"],
["sorvolare", "（su）見ないふりをする", "N"],
["prostrarsi", "平伏する", "N"],
["guardone", "のぞき魔", "N"],
["commiserare", "同情する", "N"],
["giocherellare", "ふざける", "N"],
["lisca", "魚の骨", "N"],
["le previsioni", "天気予報", "N"],
["rapitore", "誘拐犯", "N"],
["spilla", "ブローチ", "N"],
["guastafeste", "興をそぐ人", "N"],
["essere alle porte", "もうすぐだ", "N"],
["svago", "気晴らし、息抜き", "N"],
["fare la corte", "口説く", "N"],
["incustodito", "守られていない", "N"],
["atto secondo", "第二幕", "N"],
["spezzarsi", "割れる、砕ける、切れる", "N"],
["presagio", "予兆", "N"],
["sviare", "避ける、そらす", "N"],
["prendere per oro colato", "真に受ける", "N"],
["sempliciotto", "単純なやつ", "N"],
["sfinito", "疲れ果てた", "N"],
["sberla", "ビンタ", "N"],
["schema", "図", "N"],
["rintocco", "鐘の音", "N"],
["riecheggiare", "反響する", "N"],
["finalizzare", "目指す", "N"],
["arrendersi", "降参する", "N"],
["origliare", "立ち聞きする", "N"],
["sostenere l'esame", "試験を受ける", "N"],
["essiccare", "乾燥させる", "N"],
["polpetta", "肉団子", "N"],
["tenere d'occhio", "見張る", "N"],
["a metà", "途中で", "N"],
["in arrivo", "来るところだ", "N"],
["in eterno", "永遠に", "N"],
["al volo", "すぐに", "N"],
["con la coda tra le gambe", "しっぽを巻いて", "N"],
["esito", "結果", "N"],
["paraggi", "近所", "N"],
["gentaglia", "下賤な連中", "N"],
["scomodo", "快適でない", "N"],
["immischiarsi", "巻き込まれる、関わる", "N"],
["all'altezza", "できるレベルにある", "N"],
["scaldarsi", "熱くなる", "N"],
["mettere a repentaglio", "危険にさらす", "N"],
["gravoso", "重い、厳しい", "N"],
["avere la megio", "（su）勝つ、力で上回る", "N"],
["attaccabrighe", "口論好きな人", "N"],
["inoltrato", "夜遅い", "N"],
["flebile", "（声が）か弱い", "N"],
["dare una svolta", "方向転換する", "N"],
["per un pelo", "間一髪で", "N"],
["da cani", "最悪の", "N"],
["disprezzare", "軽蔑する", "N"],
["catapecchia", "ぼろ屋", "N"],
["sciupafemmine", "女ったらし", "N"],
["squattrinato", "一文無しの", "N"],
["recinzione", "囲い", "N"],
["sgraffignare", "こっそり盗む", "N"],
["risarcire", "弁償する", "N"],
["intrufolare", "忍び込ませる", "N"],
["buffone", "道化", "N"],
["cagnaccio", "バカ犬", "N"],
["infierire", "（su）残酷に振る舞う", "N"],
["nuotata", "水泳、泳ぐこと", "N"],
["importunare", "しつこく頼む、うるさがらせる", "N"],
["salamoia", "塩水", "N"],
["canotto", "ボート", "N"],
["strisciare", "這う", "N"],
["perspicace", "洞察力のある", "N"],
["pastone", "（水で溶いた）飼料", "N"],
["cotto", "惚れた", "N"],
["prendere una cotta", "一目惚れする", "N"],
["al verde", "お金がない", "N"],
["rubacuori", "魅力的な人", "N"],
["plagiare", "いいように操る", "N"],
["fondale", "背景", "N"],
["spiacente", "遺憾な", "N"],
["dongiovanni", "女ったらし", "N"],
["da strapazzo", "無価値な", "N"],
["riattaccare", "電話を切る", "N"],
["infimo", "最低の、最悪の", "N"],
["stufarsi", "うんざりする", "N"],
["strappalacrime", "感動的な、涙を誘う", "N"],
["sfigato", "不運な、災難の", "N"],
["nonchalance", "無関心、何気なさ", "N"],
["sgabello", "（背もたれのない）椅子", "N"],
["di peso", "負担である", "N"],
["prendere la briga", "（di）わざわざ…する", "N"],
["fusto", "幹、茎、イケメン", "N"],
["in un batter d'occhio", "あっという間に", "N"],
["a stento", "かろうじて、やっとの事で", "N"],
["trasandato", "だらしない、粗雑な", "N"],
["buttarsi a capofitto", "熱心にやる", "N"],
["pasticcio", "パイ、めちゃくちゃ、ごちゃ混ぜ", "N"],
["strusciare", "こする", "N"],
["premura", "配慮、親切", "N"],
["spillo", "ピン、留め金", "N"],
["biasimare", "非難する、批判する", "N"],
["androne", "ロビー", "N"],
["tirocinante", "研修生", "N"],
["farfugliare", "口ごもりながら話す", "N"],
["a rotta di collo", "大急ぎで", "N"],
["viscido", "陰険な、偽善的な、べとつく", "N"],
["tirare la cinghia", "節約する", "N"],
["da ora in poi", "今から", "N"],
["dabbenaggine", "バカ正直さ", "N"],
["imbronciarsi", "不機嫌になる", "N"],
["stuprare", "強姦する", "N"],
["intonarsi", "調和する、合う", "N"],
["con che coraggio", "よくも〜できるな", "N"],
["piagnucolone", "泣き虫", "N"],
["chiappe", "（複）尻", "N"],
["di fila", "連続で", "N"],
["sgobbare", "懸命に働く", "N"],
["piagnone", "泣き虫", "N"],
["guardarsi in cagnesco", "にらみ合う", "N"],
["impalato", "突っ立っている", "N"],
["baricentro", "重心", "N"],
["coccole", "（複）あやすこと、可愛がること", "N"],
["smidollato", "無気力な", "N"],
["cantare vittoria", "勝ち誇る", "N"],
["sbronzo", "酔った", "N"],
["cosa bolle in pentola", "どういうことなのか", "N"],
["scolare", "水を切る、排水する、飲み干す", "N"],
["lettiera", "寝具類", "N"],
["all'oscuro", "知らないで", "N"],
["panna montata", "ホイップクリーム", "N"],
["bestiola", "小動物", "N"],
["piromane", "放火魔", "N"],
["depravato", "堕落した人", "N"],
["a meraviglia", "すばらしく", "N"],
["rivangare", "蒸し返す", "N"],
["fronzolo", "粉飾、虚飾", "N"],
["fatiscente", "崩壊しつつある", "N"],
["rattoppo", "修繕", "N"],
["malridotto", "落ちぶれた、悪化した", "N"],
["termite", "シロアリ", "N"],
["trambusto", "大騒ぎ", "N"],
["sventolare", "はためく", "N"],
["mi si spezza il cuore", "心が痛い", "N"],
["autoerotismo", "自慰行為", "N"],
["a destra e a sinistra", "あっちこっちに", "N"],
["fioco", "ほのかな、かすかな、（声が）かすれた", "N"],
["scartoffia", "（複）紙の山、書類の山", "N"],
["impiccione", "でしゃばり、おせっかい", "N"],
["tempismo", "タイミング", "N"],
["alzare i tacchi", "立ち去る", "N"],
["cagionevole", "病弱な、病身の", "N"],
["lasciarsi alle spalle", "乗り越える", "N"],
["premessa", "序言、前提", "N"],
["pignolo", "せこい、けちくさい", "N"],
["luculliano", "豪勢な", "N"],
["rinsecchire", "（食材などが）乾く、しなびる", "N"],
["messinscena", "演出、見せかけ", "N"],
["per l'appunto", "ちょうど", "N"],
["palpeggiare", "まさぐる", "N"],
["borbottare", "不満を言う", "N"],
["bacucco", "年老いた、年寄り", "N"],
["bellimbusto", "かっこつけた男", "N"],
["becchettare", "つつく、ついばむ", "N"],
["proroga", "延期、猶予", "N"],
["accalappiacani", "野犬捕獲人", "N"],
["rognoso", "みすぼらしい", "N"],
["sbadato", "不注意な、うっかりした", "N"],
["botolo", "すぐ吠える小型犬", "N"],
["sanguisuga", "ヒル", "N"],
["a dispetto di", "〜にもかかわらず", "N"],
["ronzare", "うろつき回る", "N"],
["stronzata", "ばかげたこと、たわごと", "N"],
["pesciolino", "小魚", "N"],
["bottino", "戦利品", "N"],
["voyeuristico", "覗き趣味の", "N"],
["sfoggiare", "着飾る、見せびらかす、誇示する", "N"],
["ghigno", "皮肉な笑み、冷笑", "N"],
["spettabile", "尊敬すべき", "N"],
["travisare", "変形させる、歪曲する", "N"],
["donzella", "少女、若い娘", "N"],
["a gambe levate", "逃げる様子", "N"],
["vitto", "食料、食べ物", "N"],
["fighetto", "外見にこだわる男性", "N"],
["rigirare la frittata", "話題を変える", "N"],
["fetente", "卑しい", "N"],
["fottuto", "嫌な、忌々しい", "N"],
["torcicollo", "肩こり", "N"],
["alla svelta", "素早く", "N"],
["sul lastrico", "惨めな状態で", "N"],
["a quattr'occhi", "一対一で", "N"],
["cagna", "雌犬、うるさい女性", "N"],
["feccia", "おり、かす", "N"],
["assiderare", "凍らせる、凍えさせる", "N"],
["bambinone", "大きな子供、子供っぽい人", "N"],
["mietitrice", "刈り取り機", "N"],
["avviluppare", "包む、覆う、くるめる", "N"],
["sorbire", "ちびちび飲む、すする", "N"],
["pegno", "担保", "N"],
["banco dei pegni", "質屋", "N"],
["in ballo", "〜がかかっている、巻き込まれている", "N"],
["esternare", "表明する", "N"],
["capata", "短い訪問、顔見せ", "N"],
["esaudire", "（神などが願いを）かなえる", "N"],
["allestire", "準備をする、装備を取り付ける", "N"],
["saldo", "堅固な、頑丈な", "N"],
["che barba", "つまらない", "N"],
["festone", "花綱、懸花装飾", "N"],
["issare", "引き上げる", "N"],
["non c'è verso", "仕方がない", "N"],
["in fin dei conti", "結局のところ", "N"],
["preannunciare", "予告する", "N"],
["dimenare", "揺らす、ぶらぶらさせる", "N"],
["starnazzare", "（女性が）キャッキャと騒ぐ", "N"],
["attillato", "正装させる、着飾らせる", "N"],
["pruriginoso", "かゆい、むずがゆい、ほしい", "N"],
["baldoria", "お祭り騒ぎ", "N"],
["andazzo", "慣習、風潮", "N"],
["toletta", "鏡台、化粧台、化粧室", "N"],
["strambo", "奇異な、奇妙な", "N"],
["rammentare", "記憶している、覚えている", "N"],
["talare", "（裾が）かかとまである", "N"],
["scalciare", "蹴飛ばす", "N"],
["assecondare", "支持する、手助けする、従う", "N"],
["teppa", "チンピラ、やくざ", "N"],
["stecchito", "干からびた、やせ細った", "N"],
["dare il via", "始める", "N"],
["di proposito", "わざと", "N"],
["imbandire", "ごちそうを用意する", "N"],
["grattugiare", "（おろし金で）おろす", "N"],
["gambero", "エビ", "N"],
["a malapena", "かろうじて、どうにか", "N"],
["un sacco di grane", "いろいろな苦労", "N"],
["sano come un pesce", "とても健康だ", "N"],
["congenito", "生まれつきの", "N"],
["gridare ai quattro venti", "公に広める", "N"],
["farneticazione", "錯乱、狂乱状態", "N"],
["prole", "子、子孫", "N"],
["glutei", "尻", "N"],
["in vantaggio", "勝っている", "N"],
["imprenditoriale", "企業家の", "N"],
["trampolino di lancio", "踏み台", "N"],
["a che pro", "何のために", "N"],
["barilotto", "小柄で太った人", "N"],
["fare il tifo", "応援する", "N"],
["se fossi in te", "君の立場なら", "N"],
["scorrettezza", "不正確、間違い", "N"],
["bava", "よだれ", "N"],
["arrapare", "性的に興奮させる", "N"],
["rimbambire", "ぼける、もうろくする", "N"],
["rimpatriata", "（友人と）数年ぶりに会うこと", "N"],
["sabba", "魔女の集会", "N"],
["tra i piedi", "じゃまだ", "N"],
["dell'isolato", "ブロック、近所", "N"],
["tenere il piede in due staffe", "二股をかけている", "N"],
["straccio", "雑巾、ぼろきれ", "N"],
["a cavalluccio", "肩車で、おんぶで", "N"],
["giocherellone", "遊び好きの人", "N"],
["fare lo gnorri", "知らないふりをする", "N"],
["voltastomaco", "吐き気、いやなこと", "N"],
["vivanda", "食物、料理 ", "N"],
["di impiccio", "じゃまだ", "N"],
["sposina", "新妻", "N"],
["insulso", "バカな、愚かな", "N"],
["uscito di senno", "理性を失った", "N"],
["carabattola", "がらくた", "N"],
["grappa", "グラッパ（蒸留酒）", "N"],
["succhiotto", "おしゃぶり", "N"],
["blaterare", "くだらないことをしゃべる", "N"],
["alla macchia", "秘密に、隠れて", "N"],
["logorroico", "おしゃべり", "N"],
["landa", "荒野", "N"],
["a vicenda", "交代で", "N"],
["sembianza", "見かけ", "N"],
["sbafare", "（おごりで）がつがつ食べる", "N"],
["malvagio", "悪意のある", "N"],
["cerume", "耳垢", "N"],
["atterraggio", "着陸", "N"],
["esilarante", "楽しい", "N"],
["appianare", "解決する", "N"],
["non vedere l'ora di", "楽しみにする", "N"],
["a braccetto", "腕を組んで", "N"],
["a suo agio", "リラックスして", "N"],
["pedinare", "尾行する", "N"],
["in combutta", "共謀して", "N"],
["seminare", "ばらまく、相手を引き離す", "N"],
["per conto di", "〜の責任で", "N"],
["teso", "緊張した", "N"],
["con il cuore in mano", "心から", "N"],
["stare in piedi", "起きている", "N"],
["commiato", "暇乞い、離別", "N"],
["scroccare", "せびる", "N"],
["beare", "幸福にさせる", "N"],
["d'altra parte", "もう一方で", "N"],
["senza spina dorsale", "情けない、ふぬけな", "N"],
["fiuto", "嗅覚", "N"],
["focolare", "炉", "N"],
["per ogni evenienza", "万一のために", "N"],
["padroneggiare", "主導する、指揮をとる", "N"],
["banchettare", "宴会に出る、ごちそうを食べる", "N"],
["aggancio", "コネ", "N"],
["imbambolare", "呆然とする、ぼうっとする", "N"],
["alle porte", "もうすぐそこに来ている", "N"],
["convenevole", "（複）挨拶", "N"],
["imbroccare", "標的を射る", "N"],
["rimpinzare", "満たす、満腹にさせる、詰め込む", "N"],
["ben di dio", "ごちそう", "N"],
["elemosinare", "物乞いをする", "N"],
["d'altronde", "だが、とはいえ", "N"],
["scansafatiche", "怠け者", "N"],
["perdutamente", "必死に、がむしゃらに", "N"],
["scervellarsi", "知恵を絞る", "N"],
["in un modo o nell'altro", "どっちにせよ", "N"],
["una mezza idea", "思い当たるところがある", "N"],
["per il verso giusto", "正しい方向に、いい感じに", "N"],
["un secondo fine", "下心", "N"],
["in testa", "トップで", "N"],
["con le spalle al muro", "追い詰められて", "N"],
["cappio", "首つり縄", "N"],
["anni luce più", "ずっとずっと", "N"],
["maglione", "厚手のセーター", "N"],
["rugginoso", "さびた", "N"],
["alla larga", "遠ざかって", "N"],
["di gran lunga", "もっとずっと", "N"],
["strudel", "果物を入れたロールケーキ", "N"],
["accudire", "世話をする", "N"],
["testata", "先端、上部", "N"],
["spiccato", "際立った", "N"],
["a sangue freddo", "冷静に", "N"],
["benda", "包帯", "N"],
["a quanto pare", "見たところ", "N"],
["a disagio", "申し訳ない", "N"],
["lavandaio", "洗濯する人、洗濯屋", "N"],
["alle strette", "追い詰められて", "N"],
["radiografia", "レントゲン写真", "N"],
["idem", "同じく", "N"],
["alcunché", "何か", "N"],
["varcare", "横切る、越える", "N"],
["nutrito", "充実した", "N"],
["svolazzare", "羽ばたく", "N"],
["farfallone", "大きな蝶、浮気者", "N"],
["dimettere", "退院させる、解雇する", "N"],
["compiacere", "気に入られるようにする", "N"],
["mettere", "qc. sotto i denti ちょっと何か食べる", "N"],
["in bocca al lupo", "がんばって", "N"],
["tratteggiare", "（鉛筆などで）描く", "N"],
["avere la lingua lunga", "おしゃべりだ", "N"],
["sfolgorante", "輝かしい", "N"],
["ottenebrare", "暗くする、ぼやかす", "N"],
["gozzovigliare", "お祭り騒ぎをする", "N"],
["colpevolizzare", "悪いと感じさせる", "N"],
["balordo", "バカな", "N"],
["scorrevole", "なめらかな", "N"],
["dare retta", "耳を貸す", "N"],
["brillo", "ほろ酔いの", "N"],
["abbindolare", "籠絡する、だます", "N"],
["losco", "不審な、いかがわしい", "N"],
["trovare il sistema", "方法を見つける", "N"],
["capezzale", "病床", "N"],
["sfornare", "どんどん作る", "N"],
["scimunito", "ばかな、馬鹿者", "N"],
["indirizzarsi", "向かう", "N"],
["avi", "（複）祖先", "N"],
["manichino", "人体模型、マネキン", "N"],
["sopprimere", "除去する", "N"],
["promemoria", "覚え書き", "N"],
["detersivo", "洗剤", "N"],
["volubile", "気の変わりやすい", "N"],
["fare due passi", "散歩する", "N"],
["in sintesi", "要するに", "N"],
["in men che non si dica", "あっという間に", "N"],
["atrio", "ロビー", "N"],
["schiarire", "晴れる、夜が明ける", "N"],
["su di giri", "興奮している", "N"],
["cantilena", "退屈な話", "N"],
["pigolio", "ピーピー鳴くこと", "N"],
["inconsciamente", "無意識に", "N"],
["schizzinoso", "気難しい", "N"],
["tugurio", "ボロ屋", "N"],
["ovatta", "詰め物、パッド、脱脂綿", "N"],
["calunniare", "中傷する", "N"],
["qual buon vento ti porta", "これは珍しい、よく来たね", "N"],
["giretto", "散歩", "N"],
["adirato", "怒った", "N"],
["piede di porco", "バール", "N"],
["che machello", "なんてこった", "N"],
["ingoiare il rospo", "嫌なことを我慢する", "N"],
["sprovveduto", "無知な、未熟な", "N"],
["dare per scontato", "当然と見なす", "N"],
["stucchevole", "うんざりさせるような", "N"],
["tenere a bada", "注意している", "N"],
["boccaccia", "汚い口", "N"],
["inzupparsi", "ずぶ濡れになる", "N"],
["zucca vuota", "空のカボチャ、バカ", "N"],
["non capire un tubo", "全然理解していない", "N"],
["cieco come una talpa", "とても近眼だ", "N"],
["oltraggio", "侮辱、冒涜", "N"],
["faccia di bronzo", "厚かましい人", "N"],
["scalzare", "裸足にする、追い出す", "N"],
["ai ferri corti", "対峙している", "N"],
["braccare", "執拗に追いかける", "N"],
["logorante", "消耗させる", "N"],
["d'altro canto", "だがしかし", "N"],
["mattone", "レンガ", "N"],
["noncuranza", "無頓着さ", "N"],
["fare centro", "的中する、言い当てる", "N"],
["nisba", "何もない", "N"],
["casinista", "ゴタゴタを起こす人", "N"],
["a terra", "元気をなくした、零落した", "N"],
["ingarbugliare", "言いくるめる", "N"],
["povero in canna", "極貧の", "N"],
["appassire", "（花が）しぼむ、しなびる", "N"],
["il due di picche", "どうでもいいもの", "N"],
["saggio", "賢明な", "N"],
["salvataggio", "人命救助、予防処置", "N"],
["combriccola", "陽気な仲間", "N"],
["bufalo", "粗野な人、無知な人", "N"],
["deficiente", "バカ、能なし", "N"],
["mettere in ballo", "引き合いに出す、巻き込む", "N"],
["fare un figurone", "うまくやる ", "N"],
["frinire", "（セミが）ミンミン鳴く", "N"],
["cicala ", "セミ", "N"],
["tirocinio", "研修期間", "N"],
["non peritarsi", "ためらわない", "N"],
["nientepopodimeno", "まっすぐ", "N"],
["scartare", "捨てる", "N"],
["goliardico", "遍歴書生詩人風の", "N"],
["succube", "他人の言いなりになる人", "N"],
["sintesi", "概要", "N"],
["nel fiore degli anni", "若さの真っ盛りだ", "N"],
["morire dietro", "夢中だ", "N"],
["raggirare", "欺く", "N"],
["giornaliero", "毎日の", "N"],
["visionare", "吟味する、よく調べる", "N"],
["incavolarsi", "カッとなる", "N"],
["dire quattro", "はっきり言う", "N"],
["spudorato", "図々しい、恥知らずの", "N"],
["prendere di mira", "攻撃の的にする", "N"],
["ginnico", "体操の", "N"],
["imboscata", "待ち伏せ", "N"],
["temporeggiare", "グズグズする", "N"],
["talamo nuziale", "初夜の床", "N"],
["di grosso", "大きく", "N"],
["stipato", "詰め込まれた", "N"],
["accaparrare", "手付け金を払って押さえる", "N"],
["pollastrella", "若鶏、若い女の子", "N"],
["spassarsela", "享楽にふける", "N"],
["sbandata", "スリップ、滑ること", "N"],
["frottola", "作り話", "N"],
["colpi di coda", "負けた人の突然の反応", "N"],
["copione", "台本", "N"],
["pezzente", "乞食", "N"],
["sperperare", "浪費する、台無しにする", "N"],
["gradino", "（階段の）段", "N"],
["accoglienza", "もてなし、歓待", "N"],
["ruffiano", "ポン引き、ご機嫌取り", "N"],
["comunella", "徒党", "N"],
["fare forca", "さぼる", "N"],
["scervellato", "知恵の足りない、向こう見ずな", "N"],
["sguazzare", "しぶきを上げる、ゆったり暮らす", "N"],
["doglia", "（複）陣痛", "N"],
["cuore d'oro", "優しい心", "N"],
["accollarsi", "（仕事を）引き受ける、（罪を）かぶる", "N"],
["ciabatta", "スリッパ、ぼろ靴", "N"],
["con i piedi in terra", "地に足のついた", "N"],
["sopire", "和らげる", "N"],
["sfottere", "からかう、いじめる", "N"],
["a pieni polmoni", "胸一杯に", "N"],
["con l'acqua alla gola", "仕事を終える時間がない", "N"],
["chiassone", "騒々しい人", "N"],
["arrotare", "研ぐ、みがく", "N"],
["sottilizzare", "細かく考える、詮索する", "N"],
["sul filo di lana", "わずかな差で", "N"],
["svolta", "曲がること", "N"],
["sul da farsi", "何をするべきか", "N"],
["ausiliario", "補助の", "N"],
["nanna", "（幼）ねんね", "N"],
["sovrappensiero", "ぼーっとしている", "N"],
["provvidenziale", "幸運に恵まれた、思いがけない", "N"],
["in sintonia", "調和している", "N"],
["scialacquare", "浪費する、むだ遣いする", "N"],
["mollare l'osso", "（人のものから）手を離す、返す", "N"],
["con i fiocchi", "すばらしい", "N"],
["quello che può valere", "価値があるかわからないが", "N"],
["deliziare", "喜ぶ", "N"],
["daccapo", "再び、初めから", "N"],
["ecceppire", "反論する、異議を唱える", "N"],
["sulle spine", "窮屈な思いをしている、やきもきしている", "N"],
["nei dintorni", "周りに、そばに", "N"],
["vece", "代役", "N"],
["mandare a monte", "断念する", "N"],
["orda", "寄せ集め集団、群衆", "N"],
["stravaccarsi", "だらしなく寝そべる", "N"],
["tirare per le lunghe", "引き延ばす", "N"],
["volpino", "キツネのような、ポメラニアン", "N"],
["birbone", "ごろつき、いたずらっ子、ずるい、ひどい", "N"],
["in simbiosi", "共生関係にある", "N"],
["giù di corda", "落ち込んでいる", "N"],
["tarpare le ali", "自由を制限する", "N"],
["frignone", "泣き虫", "N"],
["fuggiasco", "逃走中の", "N"],
["comitiva", "団体、グループ", "N"],
["ciondolare", "ぶら下がる、揺れる、うろつく", "N"],
["scarseggiare", "少なくなる、欠く", "N"],
["cullare", "あやす", "N"],
["il terzo grado", "厳しい尋問", "N"],
["scorciatoia", "近道", "N"],
["setacciare", "ふるいにかける", "N"],
["benone", "たいへんよく", "N"],
["antifona", "当てこすり", "N"],
["appestato", "ペストにかかった", "N"],
["tra le grinfie", "（猛獣の）爪", "N"],
["saputello", "物知り顔の", "N"],
["svanire", "（匂い、味などが）消える、なくなる", "N"],
["paralume", "電灯のかさ", "N"],
["coscienzioso", "良心的な、熱心な", "N"],
["vigliacco", "臆病な、卑怯な", "N"],
["scodinzolare ", "尾を振る、へつらう", "N"],
["stuzzichino", "スナック、おつまみ", "N"],
["rimuginare", "ひっかき回す、ひっくり返して探す", "N"],
["portone", "表玄関", "N"],
["a mo' di", "…として", "N"],
["indennizzo", "補償、賠償", "N"],
["mago", "占い師、魔法使い", "N"],
["pattuire", "取り決める", "N"],
["sparlare", "けなす、悪口を言う", "N"],
["condizionare", "条件付けをする", "N"],
["lercio", "汚い", "N"],
["all'incontrario", "…に反して", "N"],
["alberello", "若木", "N"],
["agevole", "楽な、値段が手頃な", "N"],
["frappore", "間に置く", "N"],
["una volta per tutte", "一度だけ", "N"],
["a viso aperto", "率直に、敢然と", "N"],
["a pennello", "申し分のない", "N"],
["figone", "性的に魅力がある", "N"],
["progredire", "前進する", "N"],
["vicolo cieco", "袋小路", "N"],
["sciattone", "だらしない身なりの人", "N"],
["con polso fermo", "厳しく", "N"],
["assaggio", "味見", "N"],
["modico", "適度な、手頃な", "N"],
["bisboccia", "酒宴", "N"],
["avere in pugno", "掌握している", "N"],
["pollastra", "無邪気で愛嬌のある娘", "N"],
["malfamato", "評判の悪い", "N"],
["trionfare", "勝つ", "N"],
["pappone", "大食家、ヒモ", "N"],
["melma", "泥、ぬかるみ", "N"],
["zuppo", "ずぶぬれの", "N"],
["in aggiunta", "追加して", "N"],
["starnutire", "くしゃみをする", "N"],
["tassello", "パズルのピース、はめるもの", "N"],
["piantare in asso", "見捨てる", "N"],
["smontare", "解体する", "N"],
["sventura", "不運、不運なできごと", "N"],
["a guisa di", "…のように", "N"],
["sfarzoso", "豪華な", "N"],
["abbellire", "飾り立てる", "N"],
["gradinata", "段、階段", "N"],
["giunco", "イグサ", "N"],
["finzione", "虚構、フィクション", "N"],
["crepa", "亀裂", "N"],
["casupola", "ボロ屋", "N"],
["rudere", "廃墟", "N"],
["magrolino", "やせっぽちの", "N"],
["palese", "明らかな、はっきりとした", "N"],
["spaiato", "半端な、ばらばらの", "N"],
["all'infuori", "外に", "N"],
["accorciare", "短くする", "N"],
["diroccato", "半壊の", "N"],
["intimorire", "怖がらせる", "N"],
["titubare", "ためらう", "N"],
["ceffone", "平手打ち", "N"],
["sfamare", "養う", "N"],
["finanche", "…さえ", "N"],
["tiraggio", "（煙突などの）通り", "N"],
["recare", "運ぶ、持ってくる、もたらす", "N"],
["svolazzo", "フリル、装飾", "N"],
["antro", "薄暗くむさ苦しい場所", "N"],
["mettere in serbo", "蓄えておく", "N"],
["filoncino", "細長いパン、バゲット", "N"],
["festicciola", "小さなパーティー", "N"],
["insediamento", "就任、定着", "N"],
["equo", "公正な、正当な", "N"],
["assennato", "思慮分別のある", "N"],
["pavido", "おびえた", "N"],
["brocca", "水差し、つぼ", "N"],
["all'insù", "上に", "N"],
["smilzo", "やせた", "N"],
["scelleratezza", "邪悪さ、極悪非道", "N"],
["avventore", "顧客、常連", "N"],
["a galla", "水面に", "N"],
["sgranato", "さやをむいた", "N"],
["smorto", "青白い", "N"],
["intrappolare", "罠にかける", "N"],
["far fesso", "だます", "N"],
["vertenza", "紛争、けんか", "N"],
["mercanteggiare", "価格の交渉をする", "N"],
["oltremodo", "きわめて", "N"],
["indispettire", "怒らせる、いら立たせる", "N"],
["sbottare", "一時にどっと出始める", "N"],
["letizia", "喜び", "N"],
["afoso", "蒸し暑い", "N"],
["girellare", "散策する、ぶらつく", "N"],
["spallucciata", "肩をすくめること", "N"],
["nocchiero", "舵手、舵取り", "N"],
["irto", "（困難などに）満ちた、とげのある", "N"],
["brulicante", "群れなす、うじゃうじゃいる", "N"],
["ciurma", "下級船員", "N"],
["plancia", "操舵室、計器板", "N"],
["chino", "曲がった、垂れた", "N"],
["astruso", "難解な", "N"],
["indugio", "ぐずぐずすること", "N"],
["sdrucciolevole", "滑りやすい", "N"],
["parapetto", "欄干、手すり、ガードレール", "N"],
["disotto", "下に、低いところに、階下に", "N"],
["scafandro", "潜水服", "N"],
["ansante", "あえいでいる", "N"],
["immane", "巨大な", "N"],
["affetto", "（病気に）かかった", "N"],
["ammosciarsi", "ぐったりする、やる気をなくす", "N"],
["cavallone", "大波", "N"],
["deliquio", "失神、気絶", "N"],
["incolume", "無事の、無傷の", "N"],
["traversia", "逆風、逆境", "N"],
["scialuppa", "小舟、ボート", "N"],
["nuocere", "害になる、傷つける", "N"],
["pacato", "冷静な、穏やかな", "N"],
["amianto", "石綿", "N"],
["mugghiare", "とどろく", "N"],
["primigenio", "原始の", "N"],
["gòmena", "大綱", "N"],
["rullìo", "横揺れ", "N"],
["arroventato", "灼熱した", "N"],
["ridicolaggine", "ばかげたこと", "N"],
["bofonchiare", "ぶつぶつ言う", "N"],
["inabissarsi", "陥る、ふける", "N"],
["inusitato", "異常な、普通でない", "N"],
["ispido", "剛毛の", "N"],
["reputarsi", "見なす", "N"],
["ramazza", "庭ぼうき", "N"],
["stentato", "苦しい、苦心の末の", "N"],
["arguzia", "機知、頭の回転の速さ", "N"],
["volenti o nolenti", "望む望まないにかかわらず", "N"],
["contegnoso", "落ち着き払った", "N"],
["di sana pianta", "全体的に、丸ごと", "N"],
["frastornare", "疲れさせる、気を散らせる", "N"],
["spuntarla", "勝利を得る", "N"],
["vuoi", "... vuoi ... 〜も〜も", "N"],
["indefesso", "疲れを知らない", "N"],
["canzonare", "からかう", "N"],
["cenerognolo", "灰色がかった", "N"],
["bombetta", "山高帽子", "N"],
["profilare", "輪郭を描く", "N"],
["raggomitolarsi", "背を丸める、うずくまる", "N"],
["arruffato", "もつれた", "N"],
["in disparte", "離れて", "N"],
["mole", "巨大さ", "N"],
["messo", "使者", "N"],
["pago", "満足して", "N"],
["capienza", "収容能力", "N"],
["alquanto", "かなり、相当", "N"],
["sdrucciolare", "滑って転ぶ", "N"],
["tonnellata", "トン", "N"],
["tramandare", "伝える", "N"],
["cateratta", "滝", "N"],
["piedistallo", "台、礎", "N"],
["prediligere", "特に愛好する", "N"],
["screziato", "まだら模様の", "N"],
["struggimento", "思い焦がれること", "N"],
["babbuccia", "毛糸の靴", "N"],
["dama", "チェッカー", "N"],
["infrangere", "（約束を）破る", "N"],
["calvizie", "はげ頭", "N"],
["afono", "声の出ない", "N"],
["taccuino", "手帳", "N"],
["di rimando", "すぐさま答えて", "N"],
["deglutire", "飲み込む", "N"],
["inchiodare", "釘で打ちつける", "N"],
["mellifluo", "甘ったるい、口先のうまい", "N"],
["violaceo", "すみれ色の", "N"],
["inezia", "つまらないもの", "N"],
["incurante", "無頓着な", "N"],
["sbarrare", "柵でふさぐ、封鎖する", "N"],
["vincolo ", "固い絆", "N"],
["stirare", "アイロンをかける、ぴんと張る", "N"],
["decuplo", "十倍", "N"],
["inarcare", "湾曲させる", "N"],
["peraltro", "そうは言っても", "N"],
["ambo", "双方の", "N"],
["rombare", "轟音を立てる", "N"],
["soffregare", "少しこする", "N"],
["fluttuare", "波打つ", "N"],
["aculeo", "とげ、毒針", "N"],
["attacchino", "広告を貼る人", "N"],
["raffigurare", "表す、識別する", "N"],
["amareggiato", "つらい", "N"],
["molteplice", "多重の、多数の", "N"],
["rettifilo", "直線コース", "N"],
["contesa", "争い、けんか", "N"],
["baruffa", "激しい口論", "N"],
["sconcertare", "調子を狂わせる、だいなしにする", "N"],
["passettino", "よちよち歩き", "N"],
["sbrindellato", "引き裂かれた、ぼろぼろの", "N"],
["monticello", "小山", "N"],
["manciata", "ひとつかみ", "N"],
["ghignare", "あざ笑う", "N"],
["smammare", "ずらかる", "N"],
["crucciato", "怒った", "N"],
["scocciare", "うんざりさせる", "N"],
["sbarazzarsi", "厄介払いする", "N"],
["insudiciare", "よごす", "N"],
["perdigiorno", "暇人", "N"],
["risma", "（軽蔑）種類、人種", "N"],
["ingrugnito", "不機嫌な", "N"],
["mansarda", "屋根裏部屋", "N"],
["scemenze", "（複）愚かな言動", "N"],
["calcina", "石灰、モルタル", "N"],
["sfasciarsi", "壊れる、つぶれる", "N"],
["ortica", "イラクサ", "N"],
["rubicondo", "（顔色が）赤い", "N"],
["trafficare", "忙殺される", "N"],
["pignatta", "深鍋", "N"],
["sbatacchiare", "あちこちに当てる", "N"],
["rintanare", "穴に追い込む", "N"],
["fare fagotto", "急いで立ち去る、旅立つ", "N"],
["raggiante", "（精神的に）晴れ晴れとした", "N"],
["gracidare", "しゃがれ声で話す", "N"],
["fringuello", "ズアオアトリ", "N"],
["gracchiare", "しゃがれ声で話す", "N"],
["appigliarsi", "すがる", "N"],
["torrido", "酷熱の", "N"],
["vampa", "火炎、熱風", "N"],
["pupattola", "人形", "N"],
["equipaggiamento", "装備", "N"],
["amazzone", "アマゾネス、女性用乗馬服", "N"],
["schiudere", "（ゆっくりと、半ば）開く", "N"],
["braccialetto", "ブレスレット", "N"],
["soppesare", "手で重みを計る、吟味する", "N"],
["su misura", "オーダーメイドの", "N"],
["stravolgersi", "身をよじる", "N"],
["belluria", "華美、きれいなもの", "N"],
["di soppiatto", "こっそりと、隠れて", "N"],
["mozzicone", "切り取られた・焼け残ったもの", "N"],
["prorompere", "あふれ出す、吹き出す", "N"],
["autonomo", "自主独立の、自律的な", "N"],
["travagliato", "苦しみの多い", "N"],
["salassare", "血を取る、（金を）しぼり取る", "N"],
["immagazzinare", "倉庫に貯蔵する、蓄積する", "N"],
["bramoso", "熱望している", "N"],
["rantolo", "あえぎ", "N"],
["stordimento", "めまい、ぼうっとした状態", "N"],
["scrollare", "振る、揺り動かす", "N"],
["fumigare", "煙を出す、湯気を立てる", "N"],
["sfavillare", "光り輝く", "N"],
["travolgere", "なぎ倒す、壊滅させる", "N"],
["calcestruzzo", "コンクリート", "N"],
["mobilitare", "動員する", "N"],
["frac", "燕尾服", "N"],
["finanziera", "フロックコート", "N"],
["fiaccolata", "夜の松明行列", "N"],
["adunata", "集会、会合", "N"],
["ritardatario", "遅刻者、滞納者", "N"],
["cicaleccio", "（大勢の人の）話し声", "N"],
["perbenino", "ちゃんとした、きちんとした", "N"],
["svelare", "暴く、明らかにする", "N"],
["a bizzeffe", "ふんだんに、有り余るほど", "N"],
["assicella", "板きれ", "N"],
["intralciare", "じゃまする、阻害する", "N"],
["sentore", "手がかり、気配", "N"],
["purpureo", "赤紫の", "N"],
["vocìo", "騒ぎ声", "N"],
["penuria", "欠乏", "N"],
["calcinaccio", "漆喰片", "N"],
["zampettare", "（小動物が）ちょこちょこ走る", "N"],
["striscione", "横断幕", "N"],
["rimpicciolire", "いっそう小さくなる", "N"],
["rintuzzare", "はねつける", "N"],
["conciliabolo", "秘密会議、悪事の相談", "N"],
["mulinare", "回す", "N"],
["bioccolo", "（綿などの）一ふさ", "N"],
["soffiare", "息を吹く、吹きつける", "N"],
["pigiare", "踏み込む、押し込む", "N"],
["perlustrare", "巡回する", "N"],
["scrollata", "振ること、肩をすくめること", "N"],
["sentiero", "小道、細道", "N"],
["frastuono", "騒音、大音響", "N"],
["sovraccarico", "積み過ぎた", "N"],
["policromo", "多色の", "N"],
["branda", "キャンプ用折り畳み式ベッド", "N"],
["informe", "無形の", "N"],
["risvolto", "（服の）折り返し", "N"],
["appollaiarsi", "（鳥が枝などに）止まる", "N"],
["appostare", "待ち伏せる", "N"],
["sbocco", "流し口、はけ口", "N"],
["testuggine", "亀、ウミガメ", "N"],
["carraio", "車の通る", "N"],
["cantina", "地下のワイン貯蔵室、穴蔵", "N"],
["acciuffare", "捕まえる", "N"],
["far spiccare", "くっきりと見せる", "N"],
["zoccolo", "木靴、台座", "N"],
["accecare", "盲目にする", "N"],
["poggiare", "もたせかける、基礎を置く、立つ", "N"],
["stremato", "体力を使い果たした", "N"],
["encomiare", "賞賛する、ほめたたえる", "N"],
["cantonata", "（建物の）角", "N"],
["incrostare", "沈殿物で覆う、外皮で覆う", "N"],
["sporgenza", "突起", "N"],
["a ritroso", "後戻りして", "N"],
["nel contempo", "同時に", "N"],
["compatto", "ぎっしり詰まった、堅い", "N"],
["bassorilievo", "薄肉彫り", "N"],
["poderoso", "たくましい", "N"],
["compitare", "ゆっくり読む、たどたどしく読む", "N"],
["tonfo", "ドンという音", "N"],
["caracollare", "あちこち走り回る", "N"],
["accoccolarsi", "うずくまる", "N"],
["gremito", "いっぱいの、ぎっしり詰まった", "N"],
["sprezzante", "軽蔑した", "N"],
["testé", "先ほど", "N"],
["menare il can per l'aia", "長く引き延ばす", "N"],
["babele", "大混乱", "N"],
["ignaro", "…を知らない", "N"],
["a iosa", "おびただしく、ふんだんに", "N"],
["insediare", "任じる、（要職に）就く、陣取る", "N"],
["arraffare", "ひったくる、略奪する", "N"],
["allettare", "誘惑する", "N"],
["diaria", "日当", "N"],
["carpire", "だまし取る、ひったくる", "N"],
["riverire", "あいさつする", "N"],
["inerme", "武器を持たない", "N"],
["ordito", "織物、縦糸", "N"],
["rifulgere", "きらめく", "N"],
["clessidra", "砂時計", "N"],
["carillon", "オルゴール", "N"],
["zampillo", "噴出、ほとばしり", "N"],
["canterino", "鳴き声のよい", "N"],
["merletto", "（布の）レース", "N"],
["tempestare", "宝石で飾る", "N"],
["calotta", "ふた、キャップ", "N"],
["quadrante", "四分儀、文字盤", "N"],
["sovrapposto", "積み重ねた", "N"],
["ravvisare", "見分ける、識別する", "N"],
["schioccare", "パチンと鳴らす", "N"],
["in un battibaleno", "一瞬の間に", "N"],
["strizzare l'occhio", "ウィンクする", "N"],
["ricurvo", "ひどく曲がった", "N"],
["imbottito", "詰め物入りの", "N"],
["panciuto", "太鼓腹の", "N"],
["avana", "薄茶色の", "N"],
["macinare a due palmenti", "がつがつ食う", "N"],
["dimestichezza", "熟練", "N"],
["aggrovigliare", "もつれさせる", "N"],
["sibillino", "神秘的な", "N"],
["strabico", "斜視の", "N"],
["stanghetta", "メガネのつる", "N"],
["soneria", "ベル装置、アラーム", "N"],
["partecipe", "分かち合った", "N"],
["carapace", "（亀の）甲羅", "N"],
["ridda", "大騒ぎ、騒動", "N"],
["imbeccata", "入れ知恵", "N"],
["garbare", "気に入る", "N"],
["sottosopra", "逆さまに、動転して", "N"],
["usignolo", "ナイチンゲール", "N"],
["sconfinato", "果てしない", "N"],
["eccelso", "優秀な、非凡な", "N"],
["stagnare", "よどむ", "N"],
["brunito", "光沢を出した", "N"],
["fulgido", "光り輝く", "N"],
["avvizzire", "しおれる、枯れる", "N"],
["schiudersi", "（花などが）開く", "N"],
["discosto", "かけ離れた", "N"],
["impareggiabile", "無比の", "N"],
["fantasmagoria", "（千変万化の）映像", "N"],
["frangente", "砕ける波", "N"],
["costiera", "海岸", "N"],
["fragore", "大音響", "N"],
["sacrario", "聖所", "N"],
["ricciuto", "巻き毛の", "N"],
["sgorgare", "噴出する", "N"],
["stramberia", "突飛な言動", "N"],
["spossato", "ぐったりした", "N"],
["sotterfugio", "ずるい巧妙な手段", "N"],
["trapunta", "キルティングの掛け布団", "N"],
["struggersi", "思い焦がれる、苦しむ", "N"],
["atono", "無表情の", "N"],
["ciarlatano", "いかさま師", "N"],
["zimbello", "笑いもの", "N"],
["spazientito", "いら立った", "N"],
["rinfrancarsi", "自信を取り戻す", "N"],
["gratella", "グリル、焼き網", "N"],
["sgrammaticato", "文法の誤りが多い", "N"],
["appurare", "検査する", "N"],
["spiattellare", "軽率にぺらぺらしゃべる", "N"],
["difilato", "さっさと、一目散に", "N"],
["potestà", "権力", "N"],
["censimento", "国勢調査", "N"],
["salato", "（値段が）高い", "N"],
["nocca", "指関節", "N"],
["il groppo in gola", "胸のつかえ", "N"],
["irruzione", "押し入ること", "N"],
["parlottare", "ひそひそ話す", "N"],
["vetrata", "ガラス戸、ガラス窓", "N"],
["campeggiare", "目立つ、そびえる", "N"],
["raccapezzarsi", "状況を把握する、見当を付ける", "N"],
["manco l'ombra", "影も形もない", "N"],
["destreggiarsi", "困難をうまく乗り切る", "N"],
["pigia pigia", "大群衆、大混雑", "N"],
["pervenire", "着く、到達する", "N"],
["sborsare", "支払う、出費する", "N"],
["insolentire", "無礼なことを言う、罵る", "N"],
["marmocchio", "子供、ガキ", "N"],
["posata", "フォークセット", "N"],
["astante", "（複）居合わせた人、観衆", "N"],
["stomacare", "吐き気を催させる", "N"],
["inferocito", "獰猛になった、かっとなった", "N"],
["spintone", "一突き、一押し", "N"],
["spicciarsi", "急ぐ", "N"],
["marmotta", "のろま", "N"],
["iracondo", "怒りっぽい", "N"],
["metter radici", "根を下ろす", "N"],
["truciolo", "削りくず", "N"],
["prato", "芝生", "N"],
["domestico", "執事、召使い", "N"],
["levriero", "グレーハウンド", "N"],
["lacchè", "卑屈な追従者", "N"],
["schivare", "避ける、かわす", "N"],
["tenerume", "行きすぎた感傷、軟骨", "N"],
["negriero", "人使いの荒い人", "N"],
["egregio", "抜きん出た（敬称）", "N"],
["leccarsi le dita", "おいしく食べる", "N"],
["genìa", "（軽蔑）連中、部類", "N"],
["mugolare", "すすり泣く", "N"],
["grifagno", "獰猛な", "N"],
["sconvolto", "動転した", "N"],
["spalletta", "欄干、手すり", "N"],
["incurvire", "（腰が）曲がる", "N"],
["ricolmo", "…であふれんばかりの", "N"],
["mozzo", "途切れた", "N"],
["schedario", "カード箱", "N"],
["rimbombo", "轟音、反響", "N"],
["funambolo", "綱渡り芸人", "N"],
["impigliarsi", "捕らわれる、からまる", "N"],
["attorcigliarsi", "巻き付く、からまる", "N"],
["scompigliare", "かき乱す、ひっくり返す", "N"],
["scoppiettare", "パチパチ音を立てる", "N"],
["sulle prime", "はじめは、すぐには", "N"],
["ritemprarsi", "新たな力を得る", "N"],
["gracidìo", "（カエルなどの）鳴き声", "N"],
["piccolezza", "取るに足らないもの ", "N"],
["intirizzire", "凍える、かじかむ", "N"],
["stridulo", "耳をつんざくような、鋭い", "N"],
["racimolare", "苦心してかき集める", "N"],
["ghermire", "ツメでつかむ、ひったくる", "N"],
["falsetto", "裏声", "N"],
["sopraggiungere", "不意に来る", "N"],
["cinereo", "灰色の", "N"],
["menzionare", "…に言及する、述べる", "N"],
["stordito", "仰天した", "N"],
["lesto", "すばやい", "N"],
["altroché", "もちろん", "N"],
["almanaccare", "思索を巡らす", "N"],
["strascicarsi", "這っていく", "N"],
["piazzale", "大広場", "N"],
["crepitìo", "カサコソ鳴る音", "N"],
["ridacchiare", "馬鹿にして笑う、嘲笑する", "N"],
["arrancare", "びっこを引きながら歩く", "N"],
["strozza", "（俗）のど", "N"],
["tafferuglio", "乱闘", "N"],
["palloncino", "風船", "N"],
["involucro", "包むもの", "N"],
["prelibato", "美味な", "N"],
["turbinìo", "渦、ぐるぐる回ること", "N"],
["foschìa", "もや、霞", "N"],
["viscoso", "ねばつく", "N"],
["cornicione", "軒蛇腹", "N"],
["caligine", "霧、スモッグ", "N"],
["vessatorio", "圧政の、人民を虐げる", "N"],
["esile", "弱々しい、わずかな", "N"],
["arrestarsi", "止まる", "N"],
["sussulto", "びくっと動くこと", "N"],
["pattuglia", "パトロール、偵察", "N"],
["vociare", "がやがや騒ぐ", "N"],
["a spron buttato", "全速力で", "N"],
["contrada", "地区、町", "N"],
["candido", "純白の", "N"],
["torma", "軍勢、群衆", "N"],
["scrostare", "皮を取り去る、かさぶたを取る", "N"],
["fischietto", "ホイッスル", "N"],
["imbalsamare", "剥製にする", "N"],
["avvezzo", "慣れた", "N"],
["man mano che", "…するにつれて", "N"],
["piuma", "羽根、羽毛", "N"],
["smunto", "疲れ果てた", "N"],
["annaspare", "もがく", "N"],
["grezzo", "未加工の、粗野な", "N"],
["recingere", "取り囲む", "N"],
["ruspa", "地ならし機", "N"],
["rampa", "傾斜床", "N"],
["sterro", "掘り出した土", "N"],
["scavo", "穴を掘ること、掘削", "N"],
["imbocco", "進入路、入り口", "N"],
["toboga", "小型のそり、リュージュ", "N"],
["scalpiccìo", "足を引きずって歩くこと", "N"],
["brusìo", "ざわめき", "N"],
["imperterrito", "動じない、冷静な", "N"],
["superstite", "生き残りの、生存者", "N"],
["fare carponi", "四つん這いになる", "N"],
["càrdine", "ちょうつがい", "N"],
["a destra e a manca", "至る所に", "N"],
["capitombolare", "真っ逆さまに落ちる", "N"],
["dissennato", "理性を失った", "N"],
["impossessarsi", "横取りする、占領する", "N"],
["azzuffarsi", "つかみ合いのケンカをする、殴り合う", "N"],
["ansare", "あえぐ", "N"],
["turbinare", "くるくる回る", "N"],
["rivolo", "小川", "N"],
["allegrezza", "うれしい気持ち", "N"],
["acquietarsi", "落ち着く、和らぐ、静まる", "N"],
["soffuso", "一面に広がった、満ちた", "N"],
["abbaglio", "間違い、過ち", "N"],
["accezione", "意味", "N"],
["acquisire", "入手する", "N"],
["addetto", "担当者", "N"],
["albore", "夜明け、初期段階", "N"],
["annuo", "年の", "N"],
["anta", "よろい戸", "N"],
["antinomia", "二律背反", "N"],
["anzianità", "老齢、在職期間", "N"],
["archiviare", "アーカイブする", "N"],
["arto", "四肢", "N"],
["assetto", "整理", "N"],
["autovettura", "乗用自動車", "N"],
["azzeccare", "言い当てる", "N"],
["bancale", "ベンチ", "N"],
["bolletta", "領収書", "N"],
["bracciale", "ブレスレット", "N"],
["cartellino", "ラベル、値札", "N"],
["cartiera", "製紙工場", "N"],
["cartina", "小地図", "N"],
["cartongesso", "石膏ボード", "N"],
["casomai", "もし必要なら", "N"],
["cassazione", "破棄", "N"],
["ceppo", "切り株、薪", "N"],
["chiatta", "はしけ", "N"],
["chiudibile", "折りたたみの", "N"],
["coglione", "金玉", "N"],
["consiliare", "会議の", "N"],
["convegno", "集会", "N"],
["copriletto", "ベッドカバー", "N"],
["corrispettivo", "対価、報酬", "N"],
["coscia", "もも", "N"],
["cuccare", "だます、ちょろまかす", "N"],
["decennio", "10年", "N"],
["delazione", "通報、密告", "N"],
["delega", "代表任命、委任", "N"],
["delibera", "決定、採決", "N"],
["depliant", "パンフレット", "N"],
["disdetta", "不運", "N"],
["docente", "教員", "N"],
["doga", "樽板、桶板", "N"],
["ducato", "公爵の称号", "N"],
["ecografia", "超音波検査", "N"],
["emendamento", "改良、修正", "N"],
["fatturare", "混ぜ物をする、薄める、インボイスを作る", "N"],
["gamma", "品揃え", "N"],
["graduatoria", "名簿、席次", "N"],
["gravare", "重圧がかかる、苦しめる", "N"],
["guanciale", "豚頬肉の脂身の塩漬け", "N"],
["incazzarsi", "かっとなる、キレる", "N"],
["incorniciare", "額縁をつける、囲む、囲み記事にする", "N"],
["indire", "公表する、布告する", "N"],
["infortunistica", "災害防止", "N"],
["ingranditore", "拡大鏡", "N"],
["inquadratura", "縁取り、配置", "N"],
["intestare", "標題を付ける、…の名義にする", "N"],
["intimo", "下着", "N"],
["istanza", "請求、申請", "N"],
["lido", "砂州、岸", "N"],
["limitrofo", "境界を接する", "N"],
["listino", "価格表、相場表", "N"],
["liturgia", "典礼、礼拝", "N"],
["lucidante", "光沢剤", "N"],
["marchio", "刻印、スタンプ、印鑑", "N"],
["massello", "塊、インゴット、心材、ブロック", "N"],
["massiccio", "一塊の、どっしりした、頑丈な", "N"],
["moquette", "カーペット", "N"],
["mozione", "動議", "N"],
["nomina", "任命", "N"],
["nottata", "終夜、夜間", "N"],
["odierno", "今日の、現代の", "N"],
["oltretutto", "まず第一に", "N"],
["omologazione", "規準適合認定", "N"],
["organza", "オーガンジー", "N"],
["patatina", "フライドポテト、ポテトチップス", "N"],
["pedana", "踏み台、ステップ", "N"],
["perorare", "熱弁を振るう", "N"],
["pirla", "（俗）ペニス、間抜け", "N"],
["prassi", "実務、慣行", "N"],
["presiedere", "議長となる、運営する", "N"],
["prioritario", "優先権を持つ", "N"],
["procura", "検事局", "N"],
["prosieguo", "続行、継続", "N"],
["pulmino", "小型バス", "N"],
["puntualizzare", "特定する、明確にする", "N"],
["qualora", "万一…の時には", "N"],
["quaresima", "四旬節", "N"],
["quesito", "問題、質問", "N"],
["raso", "サテン", "N"],
["regia", "演出、監督", "N"],
["retaggio", "（文）遺産", "N"],
["ribadire", "繰り返し言う、再確認する", "N"],
["ricavare", "引き抜く、抽出する", "N"],
["ricovero", "避難、収容", "N"],
["risanamento", "回復、治療", "N"],
["riscontrare", "照合する、比較する、検査して見つける", "N"],
["risiedere", "在住する、駐在する", "N"],
["ristretto", "濃い、狭い、けちな", "N"],
["ruta", "ヘンルーダ", "N"],
["salma", "遺体", "N"],
["sanatoria", "救済、追認", "N"],
["sancire", "承認する、認可する", "N"],
["sangallo", "イギリス刺繍", "N"],
["sbattere", "強く打つ、激しく叩く、泡だてる", "N"],
["scenetta", "コミカルな寸劇", "N"],
["schermo", "ディスプレイ、スクリーン", "N"],
["secchiello", "小さいバケツ", "N"],
["seduta", "会議、セッション", "N"],
["seggiolone", "ベビーチェア", "N"],
["seghetto", "糸鋸", "N"],
["sfascio", "壊滅、崩壊", "N"],
["soffermare", "少し止める、少し引き止める", "N"],
["stronzo", "糞野郎", "N"],
["suddito", "臣下、臣民", "N"],
["taluno", "いくつかの、幾人かの", "N"],
["tarocco", "タロッコ（シチリア産オレンジ）", "N"],
["trasgressione", "違反、侵犯", "N"],
["trousse", "道具箱、道具入れ", "N"],
["usufruire", "利用する、活用する", "N"],
["vaffanculo", "ばか野郎、くそったれ", "N"],
["vassallo", "家来、臣下", "N"],
["vincolante", "強制的な", "N"],
["voltura", "譲渡、名義変更", "N"],
["volturare", "譲渡する、名義変更する", "N"],
["labile", "一時的な, はかない", "N"],
["incasellare", "たなに整理して入れる", "N"],
["dependance", "（ホテルの）別館, 離れ ", "N"],
["autosufficiente", "自給自足できる", "N"],
["in sovrappiù", "さらに、そのうえ", "N"],
["dinoccolare", "捻挫させる、脱臼させる", "N"],
["incolto", "耕されていない; 教養のない", "N"],
["capigliatura", "（ふさふさした）頭髪 ", "N"],
["rincantucciare", "隅に置く", "N"],
["muriatico", "塩酸の", "N"],
["orlare", "縁どりをする; 囲む", "N"],
["coazione", "強制, 強要", "N"],
["collerico", "怒りっぽい", "N"],
["a fior di labbra", "ぼそぼそと", "N"],
["eterogeneo", "異種の, 不均質の", "N"],
["defilarsi", "(再)（他人の目から）隠れる", "N"],
["ammorbidire", "柔らかにする", "N"],
["bacheca", "掲示板; 陳列ケース ", "N"],
["salopette", "オーバーオール ", "N"],
["strattone", "引き抜くこと", "N"],
["strattone", "引き抜くこと", "N"],
["chiavistello", "差し錠", "N"],
["disgregare", "解体する; 崩壊させる", "N"],
["piscia", "(俗語)小便 ", "N"],
["paciere", "仲裁人", "N"],
["latrina", "公衆便所", "N"],
["scettico", "懐疑的な; 疑い深い", "N"],
["fascicolo", "分冊; （雑誌の）各号; 小冊子", "N"],
["percossa", "殴打; 衝突, 衝撃 ", "N"],
["carreggiata", "車線, 車道", "N"],
["contea", "伯爵領; 伯爵の称号 ", "N"],
["scribacchiare", "書き散らす, いやいや書く ", "N"],
["trincerare", "塹壕で守る; (再)塹壕で身を守る", "N"],
["sminuire", "減らす; 減る", "N"],
["goffaggine", "やぼ, 無器用さ", "N"],
["inettitudine", "不適格; 愚行 ", "N"],
["biascicare", "もぐもぐ食べる; ぼそぼそと話す ", "N"],
["trafiggere", "刺し通す; 深手を負わす", "N"],
["volteggiare", "飛び回る", "N"],
["agghiacciare", "凍らせる; ぞっとさせる", "N"],
["razzo", "ロケット、ミサイル", "N"],
["rincorrere", "追いかける", "N"],
["tritare", "細かく刻む, みじん切りにする", "N"],
["buffetto", "親指と中指でほおを軽くはじくこと ", "N"],
["concitazione", "興奮; 激情 ", "N"],
["acuire", "鋭くする", "N"],
["divisorio", "分ける, 仕切る, 隔てる ", "N"],
["aspro", "酸味のある", "N"],
["sozzura", "汚物、ごみ", "N"],
["di tanto in tanto", "たまに", "N"],
["testo", "浅鍋", "N"],
["raddolcire", "甘くする; 和らげる", "N"],
["seminterrato", "半地階 ", "N"],
["allagarsi", "(再)水浸しになる ", "N"],
["mandare per aria", "ダメにする", "N"],
["sculacciare", "（尻を）ピシャリと平手打ちする ", "N"],
["scorrazzare", "駆け回る; 歩き回る", "N"],
["floscio", "柔らかい, ぶよぶよした", "N"],
["ingobbirsi", "(再)背中が曲がる ", "N"],
["gualcire", "しわにする, しわくちゃにする ", "N"],
["scompiglio", "混乱（状態）; 大騒ぎ ", "N"],
["testolina", "変人; 軽はずみな人 ", "N"],
["zelante", "熱心な, 熱意ある", "N"],
["paonazzo", "暗い赤紫色の, 濃紫の ", "N"],
["incollare", "のりで貼る; ペーストする", "N"],
["finimondo", "大混乱, 大惨事 ", "N"],
["sballottare", "ゆする", "N"],
["rintronare", "耳をつんざく、とどろく", "N"],
["gracchio", "ベニバシガラス", "N"],
["madido", "ぬれた ", "N"],
["sparpagliare", "まき散らす, 乱雑に散らかす", "N"],
["leccalecca", "ペロペロキャンディー", "N"],
["guarnire", "供給する, 備えつける", "N"],
["irascibile", "怒りっぽい, 短気な ", "N"],
["grafico", "筆記の, 筆写の; 文字の", "N"],
["sciacquone", "トイレの水洗装置 ", "N"],
["acaro", "ダニ ", "N"],
["impetigine", "とびひ", "N"],
["scapola", "肩胛骨 ", "N"],
["frangetta", "おかっぱの切り揃えた前髪 ", "N"],
["bagnoschiuma", "バスフォーム", "N"],
["impiastro", "膏薬; 小うるさい人", "N"],
["malleabile", "展性のある; 従順な, おとなしい", "N"],
["giravolta", "くるりと回ること", "N"],
["assonnato", "眠い, 眠そうな ", "N"],
["convoglio", "一団となって移動する乗り物", "N"],
["vergato", "縞のある; 書かれた", "N"],
["scalfire", "引っかく", "N"],
["pallottola", "小球; 弾丸 ", "N"],
["venire a capo di", "解決する", "N"],
["rammarico", "残念な気持ち, つらさ", "N"],
["impuntarsi", "(再)足をふんばって歩こうとしない", "N"],
["leva", "てこ, レバー; 原動力", "N"],
["giuda", "裏切り者", "N"],
["antidiluviano", "ノアの洪水以前の; 古めかしい ", "N"],
["codino", "細いしっぽ; お下げ髪", "N"],
["tramortire", "気絶させる", "N"],
["gattoni", "四つんばいで, はって ", "N"],
["arginare", "堤防を巡らす; 阻む", "N"],
["cingere", "巻きつける; 身に着ける", "N"],
["senza mezzi termini", "率直に", "N"],
["assuefazione", "慣れ, 順応性", "N"],
["lindo", "清潔な, きちんとした", "N"],
["ciarliero", "おしゃべりな", "N"],
["ammonitore", "説教する人", "N"],
["mettere nero su bianco", "記入する", "N"],
["sbilanciare", "均衡を失わせる", "N"],
["rannuvolarsi", "曇る; 顔を曇らせる ", "N"],
["avventare", "よく考えずに言う; 投げる", "N"],
["scoramento", "落胆, 失意", "N"],
["rendere pan per focaccia", "相応の仕返しをする", "N"],
["sbocconcellare", "少しずつかじる", "N"],
["giunchiglia", "キズイセン ", "N"],
["smorfioso", "気取った", "N"],
["snobbare", "見下す", "N"],
["andare a gonfie vele", "順風満帆で進む", "N"],
["pasticcione", "いいかげんな仕事をする人; 散らかす人 ", "N"],
["ciclostile", "（手動の）輪転機 ", "N"],
["acceso", "火がついた, 点灯した;（色が）鮮やかな ", "N"],
["infilzare", "刺し通す; 数珠つなぎにする", "N"],
["spappolare", "ぐしゃぐしゃにする, つぶす", "N"],
["sterco", "（動物の）ふん ", "N"],
["sprizzare", "（水，血などが）噴出する", "N"],
["aureola", "光背, オーラ; かさ ", "N"],
["rinculare", "後ずさりする", "N"],
["candito", "砂糖漬けの, 砂糖漬けの（果）物 ", "N"],
["sventato", "軽率な, 無分別な", "N"],
["frangia", "房飾り, フリンジ", "N"],
["irrompere", "押し入る, 殺到する", "N"],
["zittire", "シッシッと野次る, シーッと叱声を発する", "N"],
["bruciacchiare", "焼け焦がす, （表面をさっと）焦がす", "N"],
["boccheggiare", "（魚が）口をぱくぱくする", "N"],
["torpore", "無気力 ", "N"],
["foulard", "スカーフ", "N"],
["prevaricazione", "（地位などの）濫用; 汚職", "N"],
["avanscoperta", "偵察隊, 斥候隊 ", "N"],
["alticcio", "ほろ酔いかげんの ", "N"],
["cameratismo", "仲間意識; 同窓の団結 ", "N"],
["nell'arco di", "〜のうちに", "N"],
["sdrucito", "ほころびた, ほつれた", "N"],
["altalenare", "シーソーで遊ぶ; 上下運動をする; 迷う ", "N"],
["pavoneggiarsi", "見えを張る; うぬぼれる", "N"],
["dilungarsi", "広がる; 敷衍する; 遠ざかる", "N"],
["a crepapelle", "度を越して, 大げさに", "N"],
["inserviente", "作業員, 用務員", "N"],
["taschino", "胸ポケット; （財布などの）仕切り ", "N"],
["a precipizio", "垂直に; まっ逆さまに", "N"],
["essere lì lì per", "今にも…しそうだ", "N"],
["avere la scorza dura", "がまん強い", "N"],
["sconcio", "みだらな, 下品な", "N"],
["fleboclisi", "点滴", "N"],
["patina", "（表面の）つや, ニス", "N"],
["straziante", "責めさいなむ, 悲痛な ", "N"],
["tergiversare", "言い逃れる; 決定を引きのばす ", "N"],
["assottigliarsi", "薄くなる", "N"],
["glassa", "糖衣", "N"],
["velina", "薄手のコピー用紙; ティッシュペーパー", "N"],
["rimboccare", "折り返す; 縫いひだをつける", "N"],
["ritemprare", "焼きを入れる; 強化する", "N"],
["stonatura", "音の調子を狂わすこと, 音痴", "N"],
["mastodontico", "巨人のような, 巨大な", "N"],
["cianfrusaglia", "がらくた, 安物 ", "N"],
["estraniarsi", "(再)疎遠になる ", "N"],
["ecolalia", "反響言語症", "N"],
["arricciare", "カールさせる, 巻き毛にする", "N"],
["controbattere", "反論する; 反攻する", "N"],
["sferragliare", "（金属製品が）ガチッと鳴る ", "N"],
["marmaglia", "悪い連中, 不良仲間", "N"],
["spanna", "手のひらの幅; わずかな長さ", "N"],
["spaurito", "おびえた, 動転した", "N"],
["liquirizia", "カンゾウ", "N"],
["stadio", "競技場, スタジアム; 段階", "N"],
["gerbillo", "アレチネズミ", "N"],
["corniolo", "ミズキ", "N"],
["abbattuto", "伐採された; がっかりした", "N"],
["prendisole", "サンドレス ", "N"],
["folata", "疾風, 突風", "N"],
["crampo", "けいれん ", "N"],
["autofficina", "自動車修理工場", "N"],
["spianare", "平らにする, 平坦にする", "N"],
["utilitaria", "小型乗用車", "N"],
["cabriolet", "オープンカー", "N"],
["pienotto", "膨らんだ、ぽっちゃりした", "N"],
["incursione", "襲撃, 急襲", "N"],
["recarsi", "行く", "N"],
["inselvatichire", "野生化する", "N"],
["aggrottare", "（まゆを）ひそめる", "N"],
["conferire", "授ける; 与える", "N"],
["sulla breccia", "(essere) 現役でばりばりやる", "N"],
["inaridito", "乾かす; 乾く", "N"],
["rastrelliera", "まぐさ台, 置きだな, 台", "N"],
["reticella", "小さい網", "N"],
["distintivo", "区別を示す; 特有な; バッジ; 記章", "N"],
["sfregare", "（物を）こする; 引きずる; 傷を付ける", "N"],
["copricapo", "帽子類, 頭にかぶるもの ", "N"],
["impilare", "（山のように）積み重ねる ", "N"],
["visiera", "（帽子の）ひさし", "N"],
["sperduto", "とまどった, 居心地悪い", "N"],
["indolenzimento", "疲労感; 無感覚, しびれ ", "N"],
["sgombrare", "かたづける", "N"],
["porcile", "豚小屋; きたない場所 ", "N"],
["funesto", "不幸をもたらす; 不幸に襲われた ", "N"],
["rapprendersi", "(再)凝固する ", "N"],
["fiumana", "大河の滔々たる流れ; 氾濫, 充満 ", "N"],
["figliolanza", "一家の子供たち ", "N"],
["monsone", "モンスーン, 季節風 ", "N"],
["da quando in qua", "いつから", "N"],
["catorcio", "壊れた道具, 古ぼけた物; 体の弱い人 ", "N"],
["zigomo", "頬骨", "N"],
["picchiettare", "軽く打つ, 軽くたたく", "N"],
["ingombro", "（場所などが）ふさがった, あふれた ", "N"],
["polistirolo", "ポリスチレン", "N"],
["ingozzare", "丸飲みする; がつがつ食べる", "N"],
["mingherlino", "やせぎすの, きゃしゃな", "N"],
["trotterellare", "小走りに駆ける", "N"],
["involtino", "肉で野菜を巻いて煮込んだもの", "N"],
["contraffare", "（声，顔などを）変える, 偽る", "N"],
["inserto", "関係書類一式, ファイル, 折り込み広告", "N"],
["astemio", "酒を飲まない", "N"],
["seguire le orme di", "〜の後を継ぐ", "N"],
["incutere", "（感情などを）抱かせる ", "N"],
["sussiego", "慇懃無礼な態度", "N"],
["aggraziato", "愛らしい; 上品な; 丁重な ", "N"],
["radicare", "根付く, 根を下ろす", "N"],
["contropartita", "相殺; 代償, 報酬 ", "N"],
["arieggiare", "風を入れる; 風をあてる; まねる", "N"],
["strizzare", "絞る; 締めつける", "N"],
["ingiallire", "黄色にする; 黄ばむ; 衰える", "N"],
["imporre", "（義務，法律などを）課す", "N"],
["teiera", "ティーポット, 急須 ", "N"],
["agli sgoccioli", "(essere)死にかけている", "N"],
["cocciutaggine", "強情 ", "N"],
["percosso", "percuotere(殴る)の過去分詞 ", "N"],
["una spina nel fianco", "じゃまなもの", "N"],
["corrosi", "侵食", "N"],
["epatico", "肝臓の", "N"],
["prodigarsi", "(再)全力を尽くす", "N"],
["avere la luna storta", "機嫌が悪い", "N"],
["saltuario", ")時たまの", "N"],
["età della pietra", "石器時代", "N"],
["ictus", "発作症状", "N"],
["annientare", "（敵を）やっつける, 殺す", "N"],
["assopirsi", "(再); まどろむ, うとうとする", "N"],
["indugiare", "ぐずぐずする, ためらう", "N"],
["nuotare nell'oro", "大金持ちだ", "N"],
["prelevare", "（金額を）引き出す", "N"],
["collirio", "点眼薬 ", "N"],
["gomitata", "ひじの一突き", "N"],
["spigolo", "（物の）角; 稜", "N"],
["sospingere", "届かせる; 伸ばす", "N"],
["smerigliare", "エメリーで磨く", "N"],
["giada", "ひすい, 玉 ", "N"],
["spiantato", "無一文になった, 没落した", "N"],
["croupier", "賭場でゲーム進行をする係", "N"],
["impronta", "しるし; 跡", "N"],
["vezzeggiare", "かわいがる, なでる ", "N"],
["essere un po' fuori", "頭が少しおかしい", "N"],
["scollare", "はがす", "N"],
["capro espiatorio", "贖罪の雄山羊", "N"],
["di punto in bianco", "突然", "N"],
["carrettiere", "馬車引き", "N"],
["bastonata", "棒たたき; 打つこと", "N"],
["sedicente", "自称の; 偽称の", "N"],
["dischiudere", "明らかにする, さらけ出す", "N"],
["refrattario", "耐熱性の; 無感覚な, 冷ややかな", "N"],
["puntare", "突き付ける; 押し当てる; （金を）賭ける", "N"],
["cangiante", "玉虫色の ", "N"],
["squillo", "高く響く音", "N"],
["stazza", "容積トン数, 積載量, 船の容量; 頑丈な体格 ", "N"],
["grugnire", "ブーブー鳴く; ぶつぶつ不平を言う", "N"],
["lenire", "和らげる ", "N"],
["impreziosire", "飾り立てる", "N"],
["lancinante", "刺すような ", "N"],
["acciambellare", "ぐるぐる巻く", "N"],
["mattonella", "板石, タイル", "N"],
["portare in palmo di mano", "大切にする", "N"],
["sfacchinare", "ほねの折れる仕事をする", "N"],
["andare per traverso", "（計画などが）うまくいかない", "N"],
["rinfrancare", "再び勇気づける; 自信を取り戻させる", "N"],
["obliquo", "斜めの, 傾いた, ゆがんだ; 不正な", "N"],
["rigenerante", "刷新する、再生させる", "N"],
["accovacciarsi", "うずくまる", "N"],
["edile", "建築の", "N"],
["bozzolo", "繭; （糸の）もつれ", "N"],
["vestibolo", "玄関の間; ロビー", "N"],
["arrovellare", "悩ます, 苦しめる", "N"],
["esanime", "生命のない, 死んだような", "N"],
["pallore", "青白さ, 蒼白 ", "N"],
["sincerarsi", "確かめる", "N"],
["bagagliaio", "荷物車; （自動車の）トランク", "N"],
["dismettere", "処分する・やめる", "N"],
["boscaglia", "藪, 灌木の茂み; 密林 ", "N"],
["speziare", "スパイスを加える", "N"],
["lurido", "胸がむかつくほどきたない", "N"],
["fiumiciattolo", "小川", "N"],
["roccia", "岩, 岩石", "N"],
["arrugginire ", "さびさせる", "N"],
["inebetito", "茫然とした; 間の抜けた", "N"],
["scolo", "排出, 排水; 排水路", "N"],
["furore", "激情; 逆上; 熱狂", "N"],
["di sfuggita", "急いで", "N"],
["incitare", "〈…するように〉刺激する", "N"],
["rullo", "ロール; ローラー, ころ", "N"],
["accodare", "縦に並べる; (再)後に並ぶ", "N"],
["costoletta", "あばらの肉; ロース肉 ", "N"],
["stralunato", "動転した ", "N"],
["inossidabile", "酸化しない, さびない ", "N"],
["pioggerella", "小雨", "N"],
["pendenza", "垂れ下がること; 傾斜", "N"],
["a braccia conserte", "腕組みして", "N"],
["occhiaia", "眼窩, 眼球孔; 目の下のくま ", "N"],
["tracolla", "ストラップ、ショルダーバッグ", "N"],
["costituirsi", "自首する", "N"],
["esporre", "展示する, 掲示する", "N"],
["piovigginare", "小雨が降る, しとしとと雨が降る ", "N"],
["sconnesso", "ばらばらの; 支離滅裂な ", "N"],
["invettiva", "悪口, 罵詈雑言 ", "N"],
["cimatura", "剪定、刈り込み", "N"],
["ingente", "巨大な; 広大な ", "N"],
["erigere", "建てる; 揚げる; 創設する", "N"],
["opuscolo", "小冊子, パンフレット ", "N"],
["patinare", "古色を帯びさせる; ニスを塗る", "N"],
["bermuda", "バーミューダ・ショーツ ", "N"],
["irruenza", "激烈; 性急, 向こう見ず ", "N"],
["mortuario", "死者の ", "N"],
["flemmatico", "冷静な; 冷淡な; 忍耐強い", "N"],
["scosso", "揺れた; 衝撃を受けた; 狼狽した", "N"],
["cantiere", "造船所; ドック; 作業場", "N"],
["fuga", "逃亡; 駆け落ち; 漏れること", "N"],
["esorcizzare", "悪魔祓いの儀式を行う", "N"],
["raggrinzire", "しわをつける", "N"],
["redine", "手綱; 統率, 掌握", "N"],
["capeggiare", "先頭に立つ; 指導する ", "N"],
["scorta", "付添い; 護衛; 蓄え, 貯蔵品", "N"],
["fiotto", "波; 潮騒; 不平, 泣き言 ", "N"],
["carotide", "頸動脈 ", "N"],
["impregnare", "…に染み込ませる", "N"],
["trachea", "気管", "N"],
["accapponare", "鳥肌が立つ (再)鳥肌が立つ ", "N"],
["ingorgare", "（水路を）詰まらせる (再)たまる", "N"],
["fragoroso", "音の大きな, 騒音の ", "N"],
["foga", "意気込み, 熱意 ", "N"],
["soprappensiero", "考え込んで; ぼんやりして ", "N"],
["importo", "金額; 総額 ", "N"],
["mora", "遅滞 (essere in mora)遅れる", "N"],
["sfrontato", "厚かましい, 恥知らずの", "N"],
["comò", "整理だんす", "N"],
["gli stipi", "陳列棚", "N"],
["tanghero", "田舎者 ", "N"],
["carogna", "死体", "N"],
["sciacquio", "すすぎ洗いすること", "N"],
["disadorno", "飾り立てない; 殺風景な", "N"],
["immusonirsi", "不機嫌な顔をする", "N"],
["baraccone", "小屋", "N"],
["ordire", "経糸を掛ける; 織る; たくらむ, 企てる", "N"],
["bramosia", "熱望, 切望", "N"],
["prateria", "草原, 牧草地帯", "N"],
["monello", "不良少年; いたずら小僧 ", "N"],
["raccoglitore", "収集家; 編集者; 紙挟み, ファイル ", "N"],
["assopire", "うとうとさせる; 和らげる; 鎮める", "N"],
["solidale", "連帯の; 連帯した", "N"],
["emaciato", "やつれた, やせこけた", "N"],
["bilico", "（不安定な）平衡状態", "N"],
["scappata", "逃走、逃げること", "N"],
["propenso", "傾いている, したいと思う", "N"],
["increscioso", "不快な; 面倒な ", "N"],
["malmenare", "虐待する, いじめる", "N"],
["da che pulpito viene la predica", "お前が言うな", "N"],
["buonanima", "故人", "N"],
["spolpare", "（肉を）そぐ; （果肉を）取る; 巻き上げる ", "N"],
["imputridite", "腐る; 腐らせる", "N"],
["saccente", "知ったかぶりの; 学者ぶった", "N"],
["ammontare", "達する, 総額になる", "N"],
["cruento", "流血の", "N"],
["scanalatura", "溝をつけること", "N"],
["raggrumare", "凝固させる, 固まらせる", "N"],
["fetore", "ひどい悪臭 ", "N"],
["smacco", "敗北 ", "N"],
["frecciata", "矢を放つこと; 辛辣な言葉", "N"],
["depurazione", "純化; 浄化; 精製 ", "N"],
["sommità", "頂上、最高のもの", "N"],
["piazzola", "小広場", "N"],
["uccelliera", "鳥小屋; 大型の鳥かご ", "N"],
["cassonetto", "ごみ収集ボックス", "N"],
["contrassegnare", "目印を付ける", "N"],
["provvedere", "備える, 準備をしておく", "N"],
["lussureggiare", "生い茂る; 満ちあふれる ", "N"],
["foro", "穴", "N"],
["schifezza", "嫌悪を感じさせるもの; 見苦しいこと", "N"],
["invischiare", "（甘言で面倒などに）引き込む, 陥れる", "N"],
["affibbiare", "（締め金などで）留める", "N"],
["scozzese", "スコットランドの", "N"],
["attiguo", "隣接している", "N"],
["cancelleria", "書記局; 公式記録所", "N"],
["compunto", "呵責に耐えない, 悔恨に満ちた ", "N"],
["stritolare", "砕く, 押しつぶす", "N"],
["svampire", "消える、衰える、衰弱する", "N"],
["guizzo", "（魚などが）ぴちぴち動くこと", "N"],
["pantano", "ぬかるんだ土地, 湿地", "N"],
["impomatare", "整髪料をつける", "N"],
["motteggiare", "冗談を言う; からかう; あざける ", "N"],
["orbo", "失明した, 目の見えない", "N"],
["inscenare", "上演する, 舞台にかける", "N"],
["tacco", "靴のかかと", "N"],
["raggiro", "策略, 奸策; 詐欺, ぺてん ", "N"],
["furbacchione", "とても悪賢い人 ", "N"],
["mastello", "（木製の）おけ, たらい ", "N"],
["sterpaglia", "低木の茂み", "N"],
["brusio", "ざわめき, サワサワいう音 ", "N"],
["abbietto", "卑しい", "N"],
["girovagare", "さすらう, 放浪する; 歩き回る ", "N"],
["mulatta", "ムラートの", "N"],
["congiuntura", "接点; 継ぎ目; 状況; 時局", "N"],
["sballare", "（包みを）解いて中身を出す; 死ぬ ", "N"],
["pista", "跡, 足跡; 小道", "N"],
["pioggerella", "小雨, こぬか雨 ", "N"],
["intorpidire", "無感覚にする; しびれさせる", "N"],
["adiacente", "近くの; 隣接した", "N"],
["colare", "（液体を）こす; 濾過する", "N"],
["dicitura", "表示; 説明書き", "N"],
["barlume", "かすかな光; 曙光; きざし ", "N"],
["apporre", "（署名，日付などを）添える", "N"],
["accollare", "（きつい仕事を）引き受けさせる", "N"],
["subdolo", "人をあざむく, 陰険な, 信用できない ", "N"],
["lesbica", "レスビアン", "N"],
["troia", "雌豚", "N"],
["brizzolato", "白髪まじりの, 初老の", "N"],
["mina", "発破孔; 地雷", "N"],
["cigolio", "キーキーという音 ", "N"],
["adibire", "用いる; 取っておく", "N"],
["trombetta", "小さならっぱ", "N"],
["scassare", "（機械を）壊す, つぶす", "N"],
["fondotinta", "（化粧品の）ファンデーション ", "N"],
["fare due più due", "簡単なことをする", "N"],
["trafila", "線材を一定の太さに仕上げる型; 手続き ", "N"],
["non stare più nella pelle", "じっとしていられない", "N"],
["dedalo", "迷宮, 迷路; 錯綜, 紛糾 ", "N"],
["scheletro", "骸骨; 骨組み", "N"],
["macilento", "やせた, 衰弱した, やつれた ", "N"],
["querulo", "不平満々の; 悲しげな ", "N"],
["mobbing", "嫌がらせ、いじめ", "N"],
["biasimo", "非難; 遺憾の意; 叱責 ", "N"],
["accertamento", "確認; 検証; 評価; 見積もり", "N"],
["puntino", "点; 三点リーダー", "N"],
["moroso", "滞納の, 遅滞の ", "N"],
["orinare", "放尿する, 小便をする ", "N"],
["inacidire", "酸っぱくする（なる）; 不機嫌になる", "N"],
["erogare", "寄付する; 供給する ", "N"],
["subappalto", "下請け", "N"],
["contraddistinguere", "目立たせる (再)目立つ", "N"],
["sprovvisto", "欠けている, 持っていない", "N"],
["ciancia", "おしゃべり, たわごと; うわさ話", "N"],
["non cavarne un ragno dal buco", "無駄な努力をする", "N"],
["profanazione", "冒涜 ", "N"],
["taurino", "雄牛の; たくましい ", "N"],
["esordire", "講演の前口上を述べる, デビューする", "N"],
["di poco conto", "重要でない", "N"],
["salvaguardare", "（権利などを）守る ", "N"],
["pudico", "恥ずかしがる, はにかみやの, 内気な ", "N"],
["polverone", "大量のほこり", "N"],
["andare a genio", "好みに合う, 気に入られる", "N"],
["arbitrio", "意志, 意向", "N"],
["ingiungere", "厳命する; 通告する ", "N"],
["moncherino", "手首を切断した腕; 切断されたもの", "N"],
["circonvallazione", "環状道路", "N"],
["papillon", "蝶ネクタイ ", "N"],
["sciatteria", "だらしなさ ", "N"],
["tetraggine", "暗さ; 陰気さ ", "N"],
["spira", "らせんの一巻き; コイル ", "N"],
["abbronzatura", "日焼け ", "N"],
["struggeva", "溶かす、消耗させる、苦悩させる", "N"],
["retata", "網打ち; （警察の）手入れ ", "N"],
["piedipiatti", "警察官 ", "N"],
["fiche", "（かけ事に使う）チップ; 伝票; カード ", "N"],
["contaballe", "嘘つき", "N"],
["incartamento", "関係書類一式 ", "N"],
["incapricciarsi", "好きになる", "N"],
["attingere", "汲み上げる, すくう; 引き出す; 着想を得る", "N"],
["scalogna", "(fam.)不幸, 不運 ", "N"],
["olmo", "ニレの木 ", "N"],
["grondante", "流れ落ちる, したたる", "N"],
["falsario", "偽造者 ", "N"],
["strapieno", "超満員の; 満腹の ", "N"],
["infagottare", "…に厚着させる; (再)着ぶくれる", "N"],
["sconfinare", "越境する, 境界を越える", "N"],
["opulento", "けばけばしい, 冗長な ", "N"],
["a palate", "大量に, たくさん", "N"],
["rivaleggiare", "競う, 張り合う", "N"],
["conteso", "争って求められる, 羨望の的になっている ", "N"],
["scolaro", "小学生", "N"],
["diluire", "溶かす、薄める", "N"],
["lacustre", "湖の; 湖に住む ", "N"],
["sottobicchiere", "受け皿, コースター", "N"],
["fare il bello e il cattivo tempo", "横暴に振る舞う", "N"],
["suadente", "説得力のある, 人をひきつける ", "N"],
["impratichire", "慣らす; 上達させる (再)慣れる; 上達する", "N"],
["paludoso", "沼の多い; 湿地の", "N"],
["appariscente", "はでな; 人目をひく ", "N"],
["affusolato", "紡錘形の; ほっそりとした", "N"],
["fattura", "請求書", "N"],
["bonario", "気だての良い, 温和な ", "N"],
["incrinare", "ひびを入れる", "N"],
["arrossare", "赤くする, 赤く染める", "N"],
["arso", "焦げた; 燃焼した", "N"],
["denudare", "服を脱がせる, 裸にする", "N"],
["avvalorare", "価値を与える, 高める; 証拠を固める", "N"],
["diniego", "拒絶, 否認 ", "N"],
["a piene mani", "手からあふれんばかりに; 大量に", "N"],
["pallino", "的玉; 固執, 固定観念", "N"],
["accomiatare", "解雇する; 立ち退かす (再)辞去する ", "N"],
["terrapieno", "土手, 堤防; 堡塁 ", "N"],
["indiziare", "嫌疑をかける; 暗示する ", "N"],
["zanzariera", "網戸 ", "N"],
["sbrindellare", "引き裂く, ずたずたに裂く", "N"],
["raptus", "強い衝動; 発作的暴力 ", "N"],
["sopralluogo", "現場検証; 実地調査", "N"],
["temerario", "無鉄砲な; 無謀な; 軽率な ", "N"],
["lecito", "許された; 合法的な", "N"],
["cozzare", "角で突く; 激突する", "N"],
["evidenziatore", "蛍光ペン ", "N"],
["diroccare", "破壊する", "N"],
["enotera", "マツヨイグサ", "N"],
["didietro", "後ろに; (fam.)尻 ", "N"],
["avere la puzza sotto il naso", "鼻につく", "N"],
["spiccare", "もぎ取る, 引きはがす", "N"],
["bocconi", "うつぶせに", "N"],
["celare", "秘密にしておく, 黙っておく (再)隠れる", "N"],
["sontuoso", "豪奢な, 壮麗な, ぜいたくな ", "N"],
["tombino", "マンホール; 排水溝 ", "N"],
["rincuorare", "元気づける、慰める", "N"],
["orologio marcatempo", "タイムレコーダー", "N"],
["poltroncina", "平土間席 ", "N"],
["storpiare", "（身体や足を）不自由にさせる", "N"],
["tanfo", "臭気", "N"],
["infuocare", "赤く熱する (再) 燃える", "N"],
["serpentina", "曲がりくねった道", "N"],
["brulicare", "群れ集まる, うごめく; うじゃうじゃいる", "N"],
["innestare", "接ぎ木する; 移植する", "N"],
["gaio", "陽気な, 愉快な", "N"],
["convergere", "集まる, 集中する; 収斂する ", "N"],
["pazzesco", "気の狂った", "N"],
["di stucco", "(essere) （活動などが）活発さを失う", "N"],
["polizza", "証書, 証券", "N"],
["stipulare", "契約する, 締結する", "N"],
["restauro", "修復, 復旧", "N"],
["buttafuori", "呼び出し係; 舞台監督; 用心棒 ", "N"],
["galoppino", "使い走り", "N"],
["accorrere", "駆けつける", "N"],
["emicrania", "偏頭痛; 頭痛 ", "N"],
["ossequioso", "うやうやしい, 丁重な; こびへつらう", "N"],
["sandalo", "ビャクダン", "N"],
["tediare", "退屈させる", "N"],
["appisolarsi", "居眠りする", "N"],
["scaltro", "利口な; ずる賢い; 巧妙な ", "N"],
["zaffata", "不意に鼻をつく悪臭; 噴出 ", "N"],
["inalare", "吸入する ", "N"],
["sgranchirsi", "(再)（体を動かして）筋肉や関節をほぐす ", "N"],
["stantia", "古びた; 古びた臭い", "N"],
["introitare", "国庫に入れる、徴収する", "N"],
["ristrettezza", "狭いこと; 欠乏, 不足", "N"],
["ribalta", "はね上げ戸, 落とし戸", "N"],
["bacchettone", "狂信者", "N"],
["spiazzare", "相手の虚をつく", "N"],
["pressapoco", "だいたい、大雑把なやり方", "N"],
["incudine", "金敷; 砧骨 ", "N"],
["sgualdrina", "淫乱な女、売春婦", "N"],
["scabroso", "ざらざらした; やっかいな; 扱いにくい ", "N"],
["addire", "奉納する", "N"],
["tardona", "（若ぶりたがる）中年女性 ", "N"],
["districarsi", "(再) ほどける; 脱する", "N"],
["attuabilità", "実現可能性", "N"],
["strampalato", "突飛な, 風変わりな ", "N"],
["acume", "鋭さ; 激しさ ", "N"],
["striare", "線を入れる", "N"],
["ciarpame", "がらくた, ぼろ ", "N"],
["scarpiera", "シューズ・ボックス; 靴を入れる袋 ", "N"],
["adulatorio", "へつらうような, おせじの ", "N"],
["pretesa", "要求; うぬぼれ; てらい ", "N"],
["sovrastare", "上にある, 上にそびえ立つ; そびえる", "N"],
["grossista", "卸売り業者 ", "N"],
["lordura", "汚物; 卑劣な人間 ", "N"],
["sputare", "つばを吐く; 吐く, 吐き出す", "N"],
["spigliato", "のびのびした, 気さくな; 気楽な ", "N"],
["mazzata", "こん棒での一撃; 不意打ち, 不慮の事故 ", "N"],
["pettorale", "胸飾り", "N"],
["sofore", "眠気", "N"],
["tergicristallo", "ワイパー ", "N"],
["in procinto di", "ちょうど〜しようとしている", "N"],
["rammaricare", "悩ます (再)残念に思う", "N"],
["schivo", "避けたがる; 内気な", "N"],
["irruente", "猛烈な, 衝動的な", "N"],
["inceppare", "邪魔する; (再) 故障する", "N"],
["convolvolo", "セイヨウヒルガオ ", "N"],
["volatilizzare", "蒸発させる; 蒸発する", "N"],
["accingersi", "準備をする", "N"],
["perentorio", "猶予を認めない ", "N"],
["principesco", "君主の, 君主らしい; 豪勢な ", "N"],
["stiracchiare", "（手足を）ほぐす; （値段を）交渉する", "N"],
["fermacarte", "文鎮", "N"],
["tailleur", "（婦人服の）スーツ ", "N"],
["coetaneo", "同年齢の（人） ", "N"],
["edificabile", "建築できる ", "N"],
["ristagna", "(ristagnare)滞る, よどむ", "N"],
["solvibilità", "支払い能力", "N"],
["custode", "守衛, 監視員, 管理人", "N"],
["prendere due piccioni con una fava", "一挙両得となる", "N"],
["osmanto", "キンモクセイ", "N"],
["slittare", "そりで滑る; スリップする; 逸脱する", "N"],
["cavalletto", "画架, イーゼル; 台", "N"],
["tremito", "震え, 身震い; おののき", "N"],
["sepolcrale", "墓の; ぞっとする", "N"],
["torace", "胸郭", "N"],
["asportazione", "運び出すこと; 除去, 摘出 ", "N"],
["sub", "スキューバダイバー", "N"],
["reduce", "帰ってきたばかりの; 帰還者; 在郷軍人", "N"],
["spioncino", "のぞき穴, 監視穴 ", "N"],
["attorcigliare", "よじる, より合わせる", "N"],
["toeletta", "化粧室, 鏡台", "N"],
["invocare", "（神などの名を）呼んで祈る; 懇願する", "N"],
["sfavillio", "きらきら光ること", "N"],
["incagliare", "座礁する (再)座礁する", "N"],
["quisquilia", "つまらない物, くだらない事", "N"],
["sfasciare", "壊す, つぶす", "N"],
["nel mirino di", "狙われている", "N"],
["fettina", "薄切り; 薄切り肉 ", "N"],
["arrotolare", "巻く, 筒状にする ", "N"],
["sogghignare", "あざ笑う, せせら笑う, ほくそえむ ", "N"],
["un fico secco", "(non valere) 何の価値もない", "N"],
["adulare", "こびる (再)うぬぼれる ", "N"],
["smania", "動揺, いらだち", "N"],
["mezzosangue", "混血児; 雑種 ", "N"],
["sfollagente", "警棒 ", "N"],
["inviperire", "激怒する (再)激怒する", "N"],
["rischiarare", "照らす; 明瞭にする; 晴れ上がる", "N"],
["fattezza", "(主に複)顔立ち", "N"],
["tumido", "はれた; （唇が）厚い", "N"],
["flautare", "フルートのように吹く", "N"],
["individuare", "特定する, 突きとめる", "N"],
["schiumare", "…の泡（あく）を取る; 泡を出す", "N"],
["assaporare", "味わう, 賞味する; 楽しむ, 味わう", "N"],
["clavicola", "鎖骨", "N"],
["spugna", "スポンジ, 海綿", "N"],
["avere le mani in pasta", "影響力のある; 干渉する", "N"],
["abbozzare", "下絵を描く; 下準備をする", "N"],
["infeltrire", "フェルト状になる・フェルト状にする", "N"],
["terreo", "土色の", "N"],
["mettere sotto torchio", "苦しめる", "N"],
["piumino", "綿毛, ダウン", "N"],
["intirizzire", "凍えさせる, かじかませる; 凍える", "N"],
["infangare", "泥でよごす; 面目をつぶす", "N"],
["lampo", "稲光; 閃光; ひらめき", "N"],
["ascetico", "苦行者の; 禁欲的; 厳格な, 修道的な ", "N"],
["procacciatore", "手に入れようと努める人", "N"],
["spintonare", "強く押す, 相手を突き飛ばす ", "N"],
["poltiglia", "どろどろしたもの", "N"],
["strepitare", "大騒ぎをする; 大音響をたてる; わめく ", "N"],
["smaniare", "いらだつ, 動揺する; 強く望む", "N"],
["smanioso", "強く望んでいる; いらだっている", "N"],
["arrogarsi", "不当に我が物とする, 僭称する ", "N"],
["assestare", "整理する; 調整する", "N"],
["affilare", "研ぐ; みがく", "N"],
["mola", "挽き臼", "N"],
["testiera", "（馬の頭に付ける）馬具; ヘッドボード", "N"],
["imbavagliare", "さるぐつわをかませる", "N"],
["rigonfiamento", "ふくらむこと; 腫れ ", "N"],
["dilaniare", "八つ裂きにする; 苦しめる ", "N"],
["scia", "航跡", "N"],
["ineccepibile", "非難の余地のない ", "N"],
["scherno", "冷やかし, 嘲笑", "N"],
["scostare", "遠ざける, 引き離す; よける", "N"],
["raschiarsi la gola", "せきばらいをする", "N"],
["impudico", "慎みのない; 品のない ", "N"],
["insperato", "予期しなかった, 意外な ", "N"],
["taccagno", "けちな", "N"],
["gracidio", "（カエルなどが）ゲロゲロ鳴き続けること ", "N"],
["imperversare", "憤激する, 怒り狂う; 猛威を振るう", "N"],
["strepitoso", "やかましい; 大々的な, 大きな ", "N"],
["spifferare", "(fam.)うかつにしゃべる", "N"],
["faceto", "滑稽な, おどけた ", "N"],
["pregustare", "前もって味わう; 予期する; 心待ちにする ", "N"],
["toccare il cielo con un dito", "有頂天になる", "N"],
["ciccione", "(fam.)太っちょ, でぶ ", "N"],
["subacqueo", "水中の, 水生の; 海底の", "N"],
["ceffo", "鼻（面）; 人相の悪い顔（人）; ごろつき", "N"],
["sganciare", "鉤から外す, 留め金を外す", "N"],
["calcare", "踏む; 押し込む; 強調する; なぞる", "N"],
["comitato", "（公共的性格の）団体, 委員会", "N"],
["schiappa", "へたくそ、落ちこぼれ、間抜け", "N"],
["facezia", "冗談, しゃれ ", "N"],
["profluvio", "おびただしい流出; 多量 ", "N"],
["insonne", "眠れない, 不眠の", "N"],
["fagotto", "（大きく重い）包み; やぼな人", "N"],
["tondeggiare", "丸くなる", "N"],
["addentare", "かみつく; （歯車が）かむ", "N"],
["cianciare", "むだ話をする, へらず口をたたく", "N"],
["accasciarsi", "(再) 倒れる, へたり込む; 気落ちする ", "N"],
["appallottolare", "球にする (再) 球状になる; 背を丸める", "N"],
["adescare", "おびき寄せる; 誘惑する; 客引きをする", "N"],
["accucciarsi", "丸くなって寝る、しゃがむ", "N"],
["azzurrognolo", "青味がかった; あせた青色の, 青白い ", "N"],
["bolgia", "(fam.)大騒動の場所 ", "N"],
["ballatoio", "張り出し回廊; 岩棚", "N"],
["divampare", "燃え上がる, 燃えさかる; かっとなる", "N"],
["aggiungere legna al fuoco", "火に油を注ぐ", "N"],
["inestricabile", "（結び目などが）ほどけない; 込み入った ", "N"],
["accasciare", "衰弱させる, がっかりさせる", "N"],
["attanagliare", "ペンチで締める; 締め付ける; 苦しめる ", "N"],
["cordoglio", "哀悼 ", "N"],
["vellutato", "ビロードのような; なめらかで柔らかい", "N"],
["incespicare", "つまずく《in》", "N"],
["inconfutabile", "反駁できない, 拒絶できない ", "N"],
["lambiccarsi", "(再)苦心する《per》 ", "N"],
["rintracciare", "追跡する; 調査する", "N"],
["sciamare", "（ミツバチが）巣分かれする; 集団で移動する ", "N"],
["screpolatura", "ひび割れ, 亀裂; ひび, あかぎれ ", "N"],
["postazione", "砲座, 砲の設営; 配置, 配属 ", "N"],
["striatura", "筋を入れること; 筋, 線条", "N"],
["betulla", "カバノキ ", "N"],
["paglietta", "麦わら帽子", "N"],
["spossare", "消耗させる, 疲れさせる (再)疲れ果てる", "N"],
["tramutare", "移す; 別の容器へ移す; 配置転換する", "N"],
["tamponare", "詰め物をする; （傷口を）ふさぐ; 追突する ", "N"],
["intasare", "ふさぐ, 詰まらせる; (再)詰まる, ふさがる", "N"],
["sbrigativo", "手早い; （仕事などが）ぞんざいな", "N"],
["ecchimosi", "（打撲傷などによる皮下の）溢血斑 ", "N"],
["mulinello", "渦; つむじ風; （いかりの）巻き上げ機", "N"],
["ilarità", "陽気さ", "N"],
["sbaciucchiare", "しつこくキスする", "N"],
["ludoteca", "遊技場", "N"],
["alveo", "水路", "N"],
["malandato", "悪化した, 損なわれた; 腐った ", "N"],
["paccottiglia", "安物; くず, がらくた ", "N"],
["ballerina", "バレリーナ, トウシューズ; かかとの低い靴", "N"],
["scalcagnato", "（かかとの）すり減った; 身なりの貧弱な ", "N"],
["subitaneo", "突然の, 急な, 不意の", "N"],
["ritegno", "慎み", "N"],
["irridere", "嘲笑する", "N"],
["riproporre", "再提案する; 繰り返し提案する", "N"],
["scovare", "穴から追い出す; 探し出す, 発見する ", "N"],
["miscela", "混合, 混合物", "N"],
["beatitudine", "深い幸福;", "N"],
["impavido", "恐れを知らない ", "N"],
["osso sacro", "仙骨", "N"],
["incurvarsi", "(再)曲がる; たわむ ", "N"],
["esangue", "血を大量に失った; 貧血の; 青ざめた ", "N"],
["in preda a", "(essere)とりつかれている", "N"],
["plumbeo", "鉛の; 鉛色の ", "N"],
["formica", "合成樹脂塗料の一種", "N"],
["schermare", "（灯火に）覆いをかける", "N"],
["drappeggiare", "ドレープを寄せる", "N"],
["lucernari", "(lucernario)天窓, 明かり取り ", "N"],
["narcosi", "麻酔（状態） ", "N"],
["scarmigliare", "髪を乱す", "N"],
["capezzolo", "乳首", "N"],
["albeggiare", "夜が明ける", "N"],
["tumefare", "腫らす、むくませる", "N"],
["salmastro", "塩味のある; 塩を含んだ", "N"],
["legaccio", "（主に革の）ひも ", "N"],
["avvinghiarsi", "(再)しがみつく, くっつく", "N"],
["sorreggere", "（精神的に）支える, 支援する", "N"],
["relitto", "残った, 残存の;  生き残り, 残存物", "N"],
["water", "便器; 便所, トイレ ", "N"],
["olfatto", "嗅覚", "N"],
["trastullare", "（子供を）遊ばせる, あやす", "N"],
["prostrare", "衰弱させる, 疲弊させる (再)ひれ伏す", "N"],
["stupro", "婦女暴行, レイプ", "N"],
["custodia", "番をすること; 保管, 管理", "N"],
["sbudellare", "刺して重傷を負わす", "N"],
["aizzare", "（動物を）けしかける; そそのかす", "N"],
["snudare", "（武器などを）取り出す", "N"],
["agognare", "熱望する", "N"],
["tintinnare", "チリンチリンと鳴る ", "N"],
["squassare", "激しく揺さぶる, 猛烈に揺する ", "N"],
["sfrigolare", "（油などが）ジュージューいう", "N"],
["ferocia", "残忍; 獰猛; 残虐行為 ", "N"],
["angheria", "（権力などの）濫用", "N"],
["plasmare", "形作る, 造形する", "N"],
];
